### ISSUE TITLE
Unable to authorize  any action

### ISSUE THREAD

**Issue by MichalZalecki** [Tmeister/wp-api-jwt-auth#10]
Hi,

I'm receiving a valid token (according to `/jw-auth/v1/token/validate`) but I get `401 Unauthorized` eatch time I try to delete/add post or remove my own comments. I have only one admin user and there is no problem to do this using admin panel.

``` json
{"code":"rest_cannot_delete","message":"Sorry, you are not allowed to delete posts.","data":{"status":401}}
```

So, there is no difference whether I have plugin activated or not. The `/jwt-auth/v1` namespace works though.

**Comment by Tmeister** [comment]
Hi, 

Can I see the request that you send to the server?

You need to send the token in the request header in each request

https://github.com/Tmeister/wp-api-jwt-auth#sample-request-using-angularjs

**Comment by stlouisweb** [comment]
I'm seeing the same issue, using postman, I obtain a token, then supply the token as the 'Authorization' header like `Authorization: Bearer <token goes here>` Request type is `POST` endpoint is `myurl.com/wp-json/wp/v2/posts` request body is `title: test title`. 

The response is: `{
  "code": "rest_cannot_create",
  "message": "Sorry, you are not allowed to create new posts.",
  "data": {
    "status": 401
  }
}`

**Update** Don't have this issue with cURL

**Comment by passatgt** [comment]
Same issue here.
Edit: the WPEngine solution worked for me on my localhost(setup with Mamp), so i guess its not just for WPEngine.

**Comment by nirsol** [comment]
Hi all, wanted to share: I also faced this issue. After a few fiddling I found out that since postman shares the same cookie repository as Chrome, postman tries to authenticate using cookies (native nonces) AS WELL AS the header.
simply logging off as a site user in chrome solves the problem :)

@Tmeister awesome job on the plugin, please consider mentioning it in the docs

**Comment by wiseindy** [comment]
@nirsol Wow, thanks for this. I spent 2 whole days trying to figure out what was wrong. Great plugin otherwise.

@Tmeister If you could mention it in the docs, it would really help anyone else who is stuck in a similar situation. Love the plugin now that everything works :)

**Comment by viankakrisna** [comment]
@nirsol it's still doesn't work for me. `wp-json/wp/v2/users/me` still returns `rest_not_logged_in` even after I logged out from the site. Any alternative?

**Comment by Der-K-2000** [comment]
For me, too. Any idea to solve this problem?

**Comment by andrescheca** [comment]
@viankakrisna @theBear I was having the same problem, I fixed it by adding this in the .htaccess file:
RewriteEngine on
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]

This is in the Requirements section of the README file.

**Comment by hugocalderon** [comment]
I made the mistake of adding the constants after.
require_once(ABSPATH . 'wp-settings.php');
And that way I showed error.

The constants must be before.

**Comment by conschneider** [comment]
For me adding `SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1` instead of 

```
RewriteEngine on
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
```
solved the issue.

**Comment by stevefurley** [comment]
I had to logout then request a new code using postman then the added above like @conschneider `# 
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

RewriteEngine on
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`

**Comment by nicholaspretorius** [comment]
Hi folks, I have attempted the suggestions above, without success, yet. I have added the necessary statements to my wp-config.php file as indicated. Only have one admin user, the namespace works. However, auth headers are being stripped by Apache. This is my .htaccess file - it works on a local installation, however, when on my hosted version, it does not. 

``` 
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
</IfModule>
# END WordPress
```

Is the above .htaccess setup correct?
