### ISSUE TITLE
wp-json/wp/v2/posts?status=private error=400

### ISSUE THREAD

**Issue by Friis1978** [Tmeister/wp-api-jwt-auth#100]
Hello everyone, I really need some help with this issue. 

I have tried using the WP Rest api for getting some user data to a React Native App, but I'm kind of stuck with this issue, getting a Error status 400, while trying to get the posts with status= private.

This is the json returned data:
{
    "code": "rest_invalid_param",
    "message": "Invalid parameter(s): status",
    "data": {
        "status": 400,
        "params": {
            "status": "Status is forbidden."
        }
    }
}

I used the 'Authorization' key, and set it to 'Bearer 'token key'. 

This is my  .htaccess file:

# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteEngine on
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
RewriteRule . /index.php [L]
</IfModule>

# END WordPress

Can someone help me, please ?

**Comment by TranVanThanh1560519** [comment]
in post man You have to put status in the ' ' like this: 'status' . it worked.  sorry my english is very poor ^^

**Comment by billyjacoby** [comment]
IM having this exact same issue, iot works in postman but not using axios

**Comment by jon1wt** [comment]
The user who asks for the post is allowed to see them? permissions of editor or administrator level?

**Comment by billyjacoby** [comment]
Administrator level. Like I mentioned, doing this same request works in Postman, so i’m not sure why it won’t work in the browser.

Even hitting that url gives me a 400 in the browser though:

**Comment by jon1wt** [comment]
the error 400 is for some permissions or Invalid params, can you share the request?

**Comment by billyjacoby** [comment]
Sorry I responded to a different comment than I thought. My request is in the other issue relating to this that I just posted.

**Comment by billyjacoby** [comment]
the request I'm trying to make is as follows:

`https://billyjacoby-3412ca.easywp.com/wp-json/wp/v2/posts?status=any`

**Comment by billyjacoby** [comment]
i learned that it was my hosting provider that was not allowing this to work on my end.

For anyone else, if your using Namecheap's EasyWP this will not work...

**Comment by lamorbidamacchina** [comment]
Same issue here... same request is working in Postman but not in React App. It seems that if I pass to axios a parameter "status" with any value, even "public", the server response is a 400.

Example request - totally working on Postman with a logged in user / error 400 on React app in browser:
/wp-json/wp/v2/posts?status=private&_embed=1
Here's the full response
{"code":"rest_invalid_param","message":"Invalid parameter(s): status","data":{"status":400,"params":{"status":"Status is forbidden."},"details":{"status":{"code":"rest_forbidden_status","message":"Status is forbidden.","data":{"status":403}}}}}

while
/wp-json/wp/v2/posts?_embed=1
works both on Postman and in browser

Has anyone solved the issue?
