### ISSUE TITLE
[SOLVED] 403 Forbidden on /wp-json/jwt-auth/v1/token/validate

### ISSUE THREAD

**Issue by jrsarath** [Tmeister/wp-api-jwt-auth#102]
followed all steps mentioned in the docs...
added codes 
`RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]`
and
`SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`
to the htaccess, but still 403 jwt auth header not found

**Comment by jrsarath** [comment]
Solved : please note that if your web server runs with CGI handler with mod_suexec (php handler) then its impossible to pass the Authorization header via .htaccess..
you have to disable mod_suexec or change the PHP handler to suPHP

**Comment by prafullwizorbit** [comment]
I am facing same issue & try everything, so could you please provide more info about how  to disable mod_suexec. I am testing on xampp 5.6 something. 

Thanks.
