### ISSUE TITLE
Correct password returning html

### ISSUE THREAD

**Issue by samnockels** [Tmeister/wp-api-jwt-auth#113]
When I enter correct details I get HTML of the homepage as the response, and when I enter correct details, I get the following response:

```
{
    "code": "[jwt_auth] incorrect_password",
    "message": "<strong>ERROR</strong>: The username or password you entered is incorrect. <a href=\"https://mitunes.tv/my-account/lost-password/\" title=\"Password Lost and Found\">Lost your password</a>?",
    "data": {
        "status": 403
    }
}
```
which is slightly different to what your docs say should be returned.

Why am I getting different responses?

**Comment by Tmeister** [comment]
That's odd, are you using a redirect plugin or hook? there is not a single redirection in the plugin.

Best,
