### ISSUE TITLE
DELETE POST requests using token always return status 401

### ISSUE THREAD

**Issue by ambhar** [Tmeister/wp-api-jwt-auth#114]
Hi,

I have been trying to delete pages using the Wordpress API. I can successfully generate the JWT token. But, when I make POST, DELETE requests using the token, it always returns staus 401 with message "Sorry, you are not allowed to delete this post."
Response:
```
{
    "code": "rest_cannot_delete",
    "message": "Sorry, you are not allowed to delete this post.",
    "data": {
        "status": 401
    }
}
```
I am making DELETE requests using postman to url: http://www.myurl.com/wp-json/wp/v2/pages/100

Facing same problem while I tried deleting using CURL.

Authorization in headers is like Bearer <my-token>

Any help regarding this issue? Facing same issue when making POST requests.

**WORDPRESS VERSION: 4.9.6**

**Comment by Tmeister** [comment]
Hi, that error inherited from WordPress, are you sure the authenticated user can delete posts and pages?

Best,

**Comment by tornikegabisonia** [comment]
i had same problem.this is how i solved it:
in .htaccess required headers **MUST** be after RewriteEngine On.
so my .htaccess looks like that
```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /wordpress/index.php [L]
</IfModule>
```

my another problem was that i defined **JWT_AUTH_SECRET_KEY** on the bottom of wp-config.php file.so solution was that i moved it after wordpress Authentication constants.

**Comment by tornikegabisonia** [comment]
@Tmeister great plugin! can you update plugin  header file so there was not "Tested up to" warnings for latest version ?  it's works perfectly but its feels abandoned and untrust worthy when you see that warning :D
