### ISSUE TITLE
empty_username when I try to get an authentication token

### ISSUE THREAD

**Issue by Luc45** [Tmeister/wp-api-jwt-auth#119]
Hello,

When I try to send a POST to http://site.localhost/wp-json/jwt-auth/v1/token with username and password headers, both with correct admin login data, I get a 403 response like this:

{"code":"[jwt_auth] empty_username","message":"ERROR<\/strong>: The username field is empty.","data":{"status":403}}

![chrome_2018-07-28_19-23-02](https://user-images.githubusercontent.com/9341686/43361061-c5211104-929b-11e8-9c9c-a10b97cb54e9.png)

Configs:
- WordPress 4.9.7
- PHP 7.2.3

I have:
- Installed JWT Authentication for WP REST API
- Enabled PHP HTTP Authorization Header on .htaccess
- Defined JWT_AUTH_SECRET_KEY and enabled JWT_AUTH_CORS_ENABLE

What am I doing wrong?

**Comment by Luc45** [comment]
I found out.

I was sending Authorization as Header, it is supposed to go into body as form-data. In Curl, it translates to this:

```
    /**
    *   Generate a JWT token for future API calls to WordPress
    */
    private function getToken() {
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL,'http://site.localhost/wp-json/jwt-auth/v1/token');
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, "username=admin&password=Str0ngPass");

        // receive server response ...
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

        $server_output = curl_exec ($ch);
        if ($server_output === false) {
            die('Error getting JWT token on WordPress for API integration.');
        }
        $server_output = json_decode($server_output);

        if ($server_output === null && json_last_error() !== JSON_ERROR_NONE) {
            die('Invalid response getting JWT token on WordPress for API integration.');
        }

        if (!empty($server_output->token)) {
            $this->token = $server_output->token; # Token is here
            curl_close ($ch);
            return true;
        } else {
            die('Invalid response getting JWT token on WordPress for API integration.');
        }
        return false;
    }
```

**Comment by yonahrodrigues** [comment]
my solution from this problem in react: export function TOKEN_POST(body) {
  return {
    url: API_URL + "/jwt-auth/v1/token",
    options: {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    },
  };
}
