### ISSUE TITLE
Token validity when the user change his password

### ISSUE THREAD

**Issue by ghost** [Tmeister/wp-api-jwt-auth#12]
Hi, 
I'm in trouble, when the user change his password the token is still available.
That's normal ?

**Comment by Tmeister** [comment]
Hi,

Yes, it's normal, you need to think about the token lifecycle.

1. The user logins using the user and pass via the client.
2. If the credentials are correct, the token is created on the server and send it back to the client.
3. The user at some point changes the password on the admin (The client doesn't know about this change)
4. The client sent the stored token to the server to verify, the JWT just verify if the token is correct and do not check the user/pass again.

How to fix this problem?

- Do not allow the user change the password via the admin.
- You'll need to handle the password change in the client, remove the old token and create a new one using the new credentials.

**Comment by corky7** [comment]
Hi!

Thanks for your nice plugin.
How would I remove the old token?

The point is:
1. User changes the password via client
2. Once doing any action - user is presented with authorization error.
3. User logs in and gets a token. Token is valid (I checked it via /valid)
4. User always gets authorization error when doing the action with this new token.

**Comment by Nat-THS** [comment]
Hello! I would also like to know what's the best way to remove a token. In my case, I want to have a logout endpoint. Is that implemented?

**Comment by 2hamed** [comment]
I also need an invalidate endpoint, in case user logs out.

**Comment by Nat-THS** [comment]
@2hamed For what I've seen, these tokens are always valid! Until the previously set expiration date, of course. One thing you could do, [as suggested by this StackOverflow user](http://stackoverflow.com/a/23089839) is to save the token in a table and forbid your API to validate those blacklisted tokens.
But I'm not sure that is very useful.
In the end, I gave up and I'm working without a logout endpoint. The frontend simply forgets the token when the user clicks logout.

**Comment by Tmeister** [comment]
@2hamed, @Nat-THS 

I'm working on a new implementation to revoke the tokens from the admin, the workflow is something like this:

When a new token is created a `UUID` is added to the token itself and stored in the site DB, [see the code](https://github.com/Tmeister/wp-api-jwt-auth/blob/admin-ui-revoke-tokens/public/class-jwt-auth-public.php#L151-L164) 

When the plugin validates the token I'll add a new validation that takes the UUID and check the status in the DB, if the UUID was revoked the token will be invalid.

- The admin will have the ability to revoke this token in the admin UI manually
- The tokens will be revoked when the user's password change
- The token can be revoked via a new endpoint.

![Tokens Page](https://d3vv6lp55qjaqc.cloudfront.net/items/1B2c2B3J2G2t202o0J3z/Image%202017-01-18%20at%2010.55.49%20AM.png?X-CloudApp-Visitor-Id=1908589&v=bea4a052)

![User Profile](https://d3vv6lp55qjaqc.cloudfront.net/items/2z1o1k1b0I3s3D1N0s0j/Image%202017-01-18%20at%2010.56.17%20AM.png?X-CloudApp-Visitor-Id=1908589&v=78d5b8ae)

This work is still in progress.

**Comment by ssuess** [comment]
Just curious, is there any timeline on getting this particular functionality done? I would be happy to donate a little if it helps. :)

**Comment by ssuess** [comment]
Well, I went ahead and downloaded the latest and made it work myself. In case anyone is interested, I added the following around line 325 of /public/class-jwt-auth-public.php:

```
          /**
             * Now, Validate if the token has been revoked
             * TODO Validate this.
             **/
 			if ( ! isset($token->data->user->uuid)) {
                /** No UUID in the token, abort!! */
                return new WP_Error(
                    'jwt_auth_bad_request',
                    __('UUID not found in the token', 'wp-api-jwt-auth'),
                    array(
                        'status' => 403,
                    )
                );
            }
            
            if (isset($token->data->user->uuid)) {
                /** UUID does not exist in the db, abort!! */
                $uuidpost = get_page_by_title($token->data->user->uuid,OBJECT,'jwt_token');
                if($uuidpost == null) {
                return new WP_Error(
                    'jwt_auth_bad_request',
                    __('Bad UUID', 'wp-api-jwt-auth'),
                    array(
                        'status' => 403,
                    )
                );
            }}
```
And so that I could tell in the admin which user's token I wanted to delete, I also modified slightly the store token function in the same file to add username (at the end of the file):

```
private function store_token($uuid, $user, $user_agent)
    {
        $token_data = array(
            'post_type' => 'jwt_token',
            'post_title' => $uuid,
            'post_status' => 'publish',
        );
        $new_token_id = wp_insert_post($token_data);

        if ( ! is_wp_error($new_token_id)) {
            update_post_meta($new_token_id, 'jwt_user_id', $user->id);
            update_post_meta($new_token_id, 'jwt_username', $user->user_login);
            update_post_meta($new_token_id, 'jwt_user_agent', $user_agent);
            update_post_meta($new_token_id, 'jwt_status', 'active');
        }

        return $new_token_id;
    }
```

Finally, for some interface goodness, I added a column to display username in the tokens edit page (I put it in my theme's functions file):
 
```
// Add Username column to JWT token page
add_filter('manage_jwt_token_posts_columns', 'JWT_add_post_columns',10);
 
function JWT_add_post_columns($columns) {
    $columns['jwt_username'] = 'Username';
    return $columns;
}

// And fill in that column with data...
add_action('manage_posts_custom_column', 'JWT_columns_content', 10, 2);
 
function JWT_columns_content($column_name, $post_ID) {
    if ($column_name == 'jwt_username') {
        $jwtuser = get_post_meta($post_ID,'jwt_username',TRUE);
        if ($jwtuser) {
        echo $jwtuser; 
        } else {
        echo "nothing stored.";
        }              
    
    }
}
```

Hope this helps someone else who needed this in a jiffy. I am sure it isn't as elegant as what @Tmeister would have done, but I really needed this so I thought I would give it a shot.

**Comment by ssuess** [comment]
I also just built (again, probably not as elegant as @Tmeister would have) a re-auth endpoint that will automatically extend the token (with the same uuid) for another week without the user having to re-enter username and pass. If anyone wants it, let me know.

**Comment by Tmeister** [comment]
@ssuess would be great if you can make a pull request with that changes.

**Comment by ssuess** [comment]
sure @Tmeister, which ones? All of the above, or just the last part about the re-auth endpoint?

**Comment by 2hamed** [comment]
@ssuess Thanks. Would you please share all that you did? @Tmeister It would also be awesome if these changes are available in the next version.

**Comment by ssuess** [comment]
sure @2hamed I forked the project and added all my changes [here](https://github.com/ssuess/wp-api-jwt-auth).

A few notes:

- Since I have a co-existing oauth implementation, I added a couple of things to account for that, you can remove them if you want (or not, they shouldn't harm anything for those not using them)
- You can delete tokens from any user profile, or in the tokens CPT listing under users. But note that simply trashing these posts will not invalidate the token, you need to permanently delete it.
- the new /regen endpoint will take a valid token and extend it (without needing to re-authorize)
- my code changes validity of initial tokens to 1 month (you can easily change this in class-jwt-auth-public.php)

**Comment by ahmu83** [comment]
any updates on this? we seriously need a way to invalidate the issued token(s)

**Comment by ssuess** [comment]
@ahmu83 did you try my code above?

**Comment by ssuess** [comment]
FYI to everyone: I just made the following changes to my [fork](https://github.com/ssuess/wp-api-jwt-auth):

- new revoke endpoint (logout)
- all tokens will be invalidated if user changes his password.

**Comment by ahmu83** [comment]
Thanks @ssuess

**Comment by ahmu83** [comment]
@Tmeister any update on the official release date for the above updates?

**Comment by pnghai** [comment]
@Tmeister It's September now and I still waiting for this in the official plugin at Wordpress.

Thank :)

**Comment by ssuess** [comment]
@pnghai If you want you can just download my version. It works and does all that.

**Comment by isuke01** [comment]
So it has ben added to official or not ? :(
btw great job ! :D

**Comment by Tmeister** [comment]
Due to the age of this, I'm closing it.
