### ISSUE TITLE
Change token validation response

### ISSUE THREAD

**Issue by bilalCatic** [Tmeister/wp-api-jwt-auth#121]
Is it possible to edit response on token validation ? I didn't find filter for this

**Comment by Tmeister** [comment]
Hi @GotPPay no, is not possible at the moment.

Just to be clear, why do you want to edit the validation response?

Bests,

**Comment by bilalCatic** [comment]
I wanted to add some additional data to the validation response

**Comment by Tmeister** [comment]
For that, you can add more properties to the `data` attribute using the [jwt_auth_token_before_dispatch](https://github.com/Tmeister/wp-api-jwt-auth/blob/develop/public/class-jwt-auth-public.php#L165) filter.
