### ISSUE TITLE
"JWT is not configurated properly, please contact the admin"

### ISSUE THREAD

**Issue by botoxparty** [Tmeister/wp-api-jwt-auth#123]
Hey,

I keep getting this error, I have everything setup according to the instructions.

I'm using wpengine and have added the .htaccess file, as well as the AUTH _SECRET_KEY with my other keys in wp-config.php

Stuck, have no idea what it could be?

```
status: 403
message: "JWT is not configurated properly, please contact the admin"
```

**Comment by Tmeister** [comment]
Hi @botoxparty did you define the secret key on your `wp-config.php` file?

Here are more information: `https://github.com/Tmeister/wp-api-jwt-auth#installation--configuration`

Bests,

**Comment by botoxparty** [comment]
Sorry you're right, `wp-config.php` was being rejected when i was uploading it to the server and I didn't even realise.

**Comment by crifan** [comment]
duplicated as #59, so please go to #59 to see solution.
