### ISSUE TITLE
Does this plugin tighten authorization to routes?

### ISSUE THREAD

**Issue by morenoh149** [Tmeister/wp-api-jwt-auth#125]
Hello, I am working on a site that has this plugin installed. In a normal wp install a route like `/wp-json/wp/v2/tags` returns public tags. On the site I'm working on this route complains with
```
"code": "rest_not_logged_in",
"message": "You are not currently logged in.",
"data": {
"status": 401
}
}
```
does wp-api-jwt-auth cause this behavior?

**Comment by medmin** [comment]
Yes, absolutely. 

In my case, I need to retrieve all published posts and display them to all visitors. But apparently, I get a 403 without a token. It's just a simple get request for all published posts.
