### ISSUE TITLE
{"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}

### ISSUE THREAD

**Issue by prafullwizorbit** [Tmeister/wp-api-jwt-auth#130]
Hello,
         Thanks for the Great plugin , i am getting a error while sending a post request to 
http://mydomain/wp-json/jwt-auth/v1/token/validate 
& getting error like
{"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}
I apply .htaccess file rules as per suggested 
my .htaccess file is this
# BEGIN WordPress
`<IfModule` mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L] 
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
</IfModule>
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
# END WordPress

I have also changed in wp-config.php 

define('JWT_AUTH_SECRET_KEY', 'my-key');
define('JWT_AUTH_CORS_ENABLE', true); 
 
Any help is this related to CORS or i forget to accept headers or anything else please help with 404 issue.
Thanks

**Comment by prafullwizorbit** [comment]
I think i found the issue there must be something went wrong in my typescript code because postman show 200 in result.

**Comment by moonzlo** [comment]
I hope you burn in hell for not sharing a solution to this problem.

**Comment by prafullwizorbit** [comment]
I will share coffee with you there !!!
