### ISSUE TITLE
Using wc-rest-api authentication

### ISSUE THREAD

**Issue by mostafaebrahimi** [Tmeister/wp-api-jwt-auth#137]
Hi.
I installed wp-api-jwt-auth plugin but when I enable 
this plugin I can not use consumer-secret and consumer-key of woocommerce
and get this error:
```json
{
    "code": "jwt_auth_bad_auth_header",
    "message": "Authorization header malformed.",
    "data": {
        "status": 403
    }
}
```
I can not disable this feature because some of my old apps  using this feature.
how can I solve this problem ?

**Comment by mostafaebrahimi** [comment]
I solved the problem by some changes in plugin

**Comment by mstanarevic** [comment]
> I solved the problem by some changes in plugin

Can you please share your solution?

**Comment by mostafaebrahimi** [comment]
@mstanarevic Hi
I changed the plugin code
in class `public/class-jwt-auth-public.php`

```php
 public function rest_pre_dispatch($request)
 {
     if (is_wp_error($this->jwt_error)) {
         return $this->jwt_error;
     }
     return $request;
 }
```
change to 
```php
 public function rest_pre_dispatch($request)
 {
   /* if (is_wp_error($this->jwt_error)) {
         return $this->jwt_error;
     }
*/
     return $request;
 }
```
in this way when client requested to server if token was valid it will go to next step and if not it will go next step but without valid user.so in plugin you are writing you can check that user exist or not.

**Comment by mstanarevic** [comment]
> @mstanarevic Hi
> I changed the plugin code
> in class `public/class-jwt-auth-public.php`
> 
> ```
>  public function rest_pre_dispatch($request)
>  {
>      if (is_wp_error($this->jwt_error)) {
>          return $this->jwt_error;
>      }
>      return $request;
>  }
> ```
> 
> change to
> 
> ```
>  public function rest_pre_dispatch($request)
>  {
>    /* if (is_wp_error($this->jwt_error)) {
>          return $this->jwt_error;
>      }
> */
>      return $request;
>  }
> ```
> 
> in this way when client requested to server if token was valid it will go to next step and if not it will go next step but without valid user.so in plugin you are writing you can check that user exist or not.

Thanks! :)

**Comment by mostafaebrahimi** [comment]
@mstanarevic Is problem solved ?
