### ISSUE TITLE
400 on every request with status param

### ISSUE THREAD

**Issue by billyjacoby** [Tmeister/wp-api-jwt-auth#141]
Every time I try to send a request to get "private" or "any" posts from my API i get a 400 error due to pre-flight checks in the browser. 

Postman gets the correct response, but axios and fetch cannot.

Postman gets correct responses from an OPTIONS request too, so I'm not sure why this error is being thrown.

my request is as follows:

![screen shot 2019-02-14 at 7 49 51 pm](https://user-images.githubusercontent.com/27246508/52827185-b5cccd80-3091-11e9-8d2a-54c091f98d08.png)

and the error I keep getting in the console is as follow:

![screen shot 2019-02-14 at 7 50 21 pm](https://user-images.githubusercontent.com/27246508/52827193-c7ae7080-3091-11e9-8e98-5590d045a1d0.png)

My Postman request is as follows:

![screen shot 2019-02-14 at 7 51 23 pm](https://user-images.githubusercontent.com/27246508/52827226-ed3b7a00-3091-11e9-9258-c585f19158fd.png)

and my .htaccess:

![screen shot 2019-02-14 at 7 51 57 pm](https://user-images.githubusercontent.com/27246508/52827244-00e6e080-3092-11e9-9463-45e382ffd9ec.png)

EDIT:

Even when I try to hit that API endpoint from a browser, i get an error:

![screen shot 2019-02-14 at 8 34 44 pm](https://user-images.githubusercontent.com/27246508/52828740-fa5b6780-3097-11e9-9e2b-0dba74e8579b.png)

This is leading me to believe that it might be something with the actual wp rest api?

This error has been killing me, and im at the end of my rope. If anyone has any help with this issue it would be a life saver!

**Comment by jon1wt** [comment]
the problem is in the CORS, you can try with this on the functions, the problem are in the calls from localhost, and you can remove this when your app are in production


```
// Hook to allow headers and cors things on rest api
add_action( 'rest_api_init', 'wp_rest_allow_all_cors', 15 );
/**
 * Allow all CORS.
 *
 * @since 1.0.0
 */
function wp_rest_allow_all_cors() {
  // Remove the default filter.
  remove_filter( 'rest_pre_serve_request', 'rest_send_cors_headers' );
  // Add a Custom filter.
  add_filter( 'rest_pre_serve_request', function( $value ) {
    header( 'Access-Control-Allow-Origin: *' );
    header( 'Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE' );
    header( 'Access-Control-Allow-Credentials: true' );
    header( 'Access-Control-Allow-Headers: cache-control, X-WP-Nonce, Authorization, Content-Type, Access-Control-Allow-Headers, Accept' );
    return $value;
  });
}
```

**Comment by billyjacoby** [comment]
so this just goes in my wp-content/wp-includes/functions.php file?

Edit:

 I added this to the bottom of the file, and it hasn't changed anything.

**Comment by jon1wt** [comment]
yes in functions.php, try adding the code on the top

**Comment by billyjacoby** [comment]
Tried at the top too, no change =/

**Comment by jon1wt** [comment]
it's weird, it's a CORS error and that should fix it, it's not a plugin error, google the error in the CORS according to the development of your app

**Comment by billyjacoby** [comment]
I’ve been googling that and I’ve tried everything I’ve come across, no luck. 

I don’t think its a CORS error because the request works from Postman, but then the browser shows the 400 error.

Would you mind sharing how you make an authenticated request to get a private post, or something similar?

**Comment by jon1wt** [comment]
I had the same error of CORS with the request of a list of editor users on an Angular app working on local, on postman work but on localhost don't work, and then I try the code I share and work fine

**Comment by billyjacoby** [comment]
Ill push to the dev branch and see if it works, but being as when I type the same request in the browser address bar I still get the error, I’m not too hopeful.

**Comment by billyjacoby** [comment]
Okay, So I've tried using this from the web and it hasn't worked either.

Even when i try to view a specific private post by ID I'm getting a 401 error, even though it works in Postman.

There has to be something weird going on here that we can figure out. Looking through the issues, it seems that multiple people are having issues that are all related.

**Comment by rocifier** [comment]
In all of the info and screenshots, you didn't show which url you are making the api request from in the browser. That is the most important information for CORS..

**Comment by billyjacoby** [comment]
@rocifier I've tried making the requests from multiple different locations in the browser. localhost is where I'm testing and getting most of the errors, but even when i try to access the url by typing it in the browser i get a 400 error.

I've tried deploying it to billyjacoby.com and Impact getting the same errors in the console from there as well.


I still have no solution to this issue and its been killing me for over a week now, i'll try anything at this point lol.

**Comment by billyjacoby** [comment]
this was apparently an issue with the hosting provider i was using.

For anyone else who pulls their hair out over this, Namecheap's EasyWP will not work with this...

**Comment by rocifier** [comment]
Using localhost is just straight not going to work for CORS these days. It is much better to modify your HOSTS file with a legitimate looking domain name (in your case maybe something like billyjacoby-dev.com mapped to 127.0.0.1). This is what I do and everything works for me locally.

**Comment by billyjacoby** [comment]
localhost works fine now that I figured out the problem was with the hosting provider. 

and either way, i had been trying from a varlet of different hostnames. I’ve never had issue developing from localhost either.

**Comment by Mulli** [comment]
What was the problem?
Thanks

**Comment by billyjacoby** [comment]
the hosting service i was using wouldn’t allow the necessary CORs requirements to hit the api.

**Comment by thestevenkwok** [comment]
I encountered the 400 error as well, but not sure if it was related to the CORs issue like your case. I used PHP Curl to send the request and I found a solution to avoid 400: https://stackoverflow.com/questions/32944441/how-to-resolve-http-1-1-400-bad-request-in-curl-php

Add an empty array to CURLOPT_POSTFIELDS the option.
