### ISSUE TITLE
Compatibility issue with Rest API cache 

### ISSUE THREAD

**Issue by ghost** [Tmeister/wp-api-jwt-auth#142]
The plugin is not compatible with the https://wordpress.org/plugins/wp-rest-api-cache/
if you enable that plugin, this is not working any more

**Comment by Tmeister** [comment]
Well, that plugin caches all the API request is not a JWT fault.

The plugin [has a filter to skip endpoints](https://github.com/airesvsg/wp-rest-api-cache/blob/master/class-wp-rest-cache.php#L51) to be cached you should that hook to skip the JWT endpoints.
