### ISSUE TITLE
Route not found when Authorization Bearer not present

### ISSUE THREAD

**Issue by NoMan2000** [Tmeister/wp-api-jwt-auth#145]
<img width="744" alt="screen shot 2019-02-22 at 8 21 45 am" src="https://user-images.githubusercontent.com/812215/53255573-c7f2d100-367a-11e9-8549-fd57a386ba63.png">
<img width="608" alt="screen shot 2019-02-22 at 8 21 55 am" src="https://user-images.githubusercontent.com/812215/53255585-cb865800-367a-11e9-9e63-386970e93c39.png">
<img width="1024" alt="screen shot 2019-02-22 at 8 22 16 am" src="https://user-images.githubusercontent.com/812215/53255586-cb865800-367a-11e9-9f56-4a0e8ab61496.png">

Details shown above in the network capture.  When I don't put in the Authorization Bearer token, it says rest no route found.  When I add it to the request, then I get a 403 because the bearer token doesn't match.  The route is correct.  

I'm using axios as the connecting library.

```js
import axiosLib from 'axios';

const axios = axiosLib.create();

axios.interceptors.request.use(
  async config => {
    const localHeaders = {
      'X-WP-Nonce': CelestialSettings.nonce
    };
    let jwtObj = {};
    const jwt = localStorage.getItem('jwt') || '';
    if (jwt) {
      jwtObj = { Authorization: `Bearer ${jwt}` };
    }
    return {
      ...config,
      headers: {
        ...config.headers,
        ...localHeaders,
        ...jwtObj
      }
    };
  },
  error => Promise.reject(error)
);


export const createCancelSource = () => axiosLib.CancelToken.source();

export default axios;
```

And in the submit (React) I have this:

```jsx
submitLogin = (e: SyntheticEvent<>) => {
    e.preventDefault();
    const {username, password} = this.state;
    axios.post(`${api}jwt-auth/v1/token`, {
      username, password
    }).then((res) => {
      const {data} = res;
      localStorage.setItem('jwt', data.token);
      return data;
    }).catch((err) => {
      console.error(err);
    });
  };
```

**Comment by jon1wt** [comment]
I think the route is:
```
axios.post(`${api}jwt-auth/v1/token?username=${username}&password=${password}`)

```
