### ISSUE TITLE
Is there any way to generate token while registering customer?

### ISSUE THREAD

**Issue by nikeshulak** [Tmeister/wp-api-jwt-auth#155]
Is there any way to generate jwt token while registering customer via
POST /wp-json/wc/v3/customers

So, that we can directly login the user while they sign up

Thanks in advance! :)

**Comment by Steffi3rd** [comment]
$JWT->generate_token($request);

Maybe this can help: https://github.com/Tmeister/wp-api-jwt-auth/issues/50#issuecomment-275646045
