### ISSUE TITLE
Refresh token without credentials

### ISSUE THREAD

**Issue by lazharichir** [Tmeister/wp-api-jwt-auth#156]
Could we add an endpoint `/refresh` that would return a refreshed token (`jwt_auth_token_before_sign` would be called again) by using a valid `Authorization` header token?

# My use case

My architecture is as such:
- WordPress blog (WooCommerce + WC Subscriptions)
- Separate app
-- Frontend _– React App in a subdomain_
-- Backend _– AWS API Gateway + Lambda + its own DB, billing and user mngmt is done on the blog)_

A user subscribes to paid subscriptions on the main WP site. These subscriptions allow the user to use credits for the other application (React app).

That separate app's backend checks the JWT in the cloud and allows/denies access without calling the main WP site.

I use `jwt_auth_token_before_sign` to store information about the user (purchases, credits, etc) in the JWT – so the other app's backend can make decisions immediately.

**_However..._**

If the user logs in, uses my react app, then goes to the blog to buy more credits, and returns to the react app, the JWT is the same unless I force them to log out and log in again with their username/password.

**Comment by carlosen14** [comment]
Actually i was needing the same, somethings like oAuth2.0, generate a refresh token and if needed to refresh, authorize using client ID and client KEY these are kept on backend.
