### ISSUE TITLE
Algorithm not allowed

### ISSUE THREAD

**Issue by tmikeska** [Tmeister/wp-api-jwt-auth#159]
hi, I have all set correctly, .htaccess and wp-config.php, but receiving following error:

```
"code": "jwt_auth_invalid_token",
    "message": "Algorithm not allowed",
    "data": {
        "status": 403
    }
```
any advice please? thanks

**Comment by AMINEDGE** [comment]
I have the same issue

**Comment by roosri** [comment]
same here
 `{
    "code": "jwt_auth_invalid_token",
    "message": "Algorithm not allowed",
    "data": {
        "status": 403
    }
}`

**Comment by marioshtika** [comment]
Me too

**Comment by bmochief** [comment]
I have the same problem now, everything was working but now I get this error when trying to use the token in a request.

**Comment by marioshtika** [comment]
This issue is being handled here
https://github.com/Tmeister/wp-api-jwt-auth/issues/247
