### ISSUE TITLE
Won't validate login

### ISSUE THREAD

**Issue by BLamy** [Tmeister/wp-api-jwt-auth#16]
I'm trying to get this plugin working, however, whenever I attempt to login it tells me that I have invalid credentials. (yes, a user `test:test` exist)

The problem seems to be that the `$request` object passed into `generate_token` is null. 

Any idea why this would be?

I'm using the official wordpress docker container. 

![image](https://cloud.githubusercontent.com/assets/324928/13383065/07ac9928-de51-11e5-9402-29dce5726cbf.png)

**Comment by Tmeister** [comment]
Hi BLamy,

You are sending the credentials as headers, that is wrong; you should send the credentials as a JSON payload take a look.

![](https://s3.amazonaws.com/f.cl.ly/items/2u3N0J1k470o0k3U2n0A/Image%202016-02-28%20at%206.36.19%20PM.png?v=ac2bbb68)
