### ISSUE TITLE
Google Captcha (reCAPTCHA) blocks the authentication

### ISSUE THREAD

**Issue by NikolinNgjela** [Tmeister/wp-api-jwt-auth#166]
If you are using Google Captcha (reCAPTCHA) https://wordpress.org/plugins/google-captcha/ and you have activate this plugin it blocks the authentication request

https://domaintest.com/wp-json/jwt-auth/v1/token

response:

{
    "code": "[jwt_auth] incorrect_password",
    "message": "Authentication failed.",
    "data": {
        "status": 403
    }
}

**Comment by techartdev** [comment]
You saved my day man! Thank you, spent over 2 hours to figure out why it returns that. Damnn

**Comment by DrMickArtisan** [comment]
I'm experiencing the same problem here. Does anyone have a clue to a solution ?

**Comment by MikeUdin** [comment]
> You saved my day man! Thank you, spent over 2 hours to figure out why it returns that. Damnn

I have a same issue. Any ideas how to fix this?

**Comment by victormattosvm** [comment]
FIX for WP REST API or WPGraphQL: https://gist.github.com/victormattosvm/4a1781413816fb7aa8733d5c8ff6920a

**Comment by techartdev** [comment]
> > You saved my day man! Thank you, spent over 2 hours to figure out why it returns that. Damnn
> 
> I have a same issue. Any ideas how to fix this?

I know long time ago passed but no I didn't found a fix. I've migrated to OAuth which works fine with reCaptcha. Today I've decided to get back to this as I need user accounts auth and JWT is the option but I hit this problem again. No luck, the reCaptcha plugin is still blocking it. For now I'll probably remove the captcha and I'll be looking for other security solution for the forms.

**Comment by akshuvo** [comment]
I found a solution but have to edit the code directly in the `google-captcha/google-captcha.php` file. 


```php
if ( ! function_exists( 'gglcptch_is_recaptcha_required' ) ) {
	function gglcptch_is_recaptcha_required( $form_slug = '', $is_user_logged_in = null ) {
		global $gglcptch_options;

		if ( is_null( $is_user_logged_in ) ) {
			$is_user_logged_in = is_user_logged_in();
		}

		if ( empty( $gglcptch_options ) ) {
			$gglcptch_options = get_site_option( 'gglcptch_options' );
			if ( empty( $gglcptch_options ) ) {
				register_gglcptch_settings();
			}
		}

		// Here is a disabling reCaptcha for all json requests
		if ( wp_is_json_request() ) {
			return false;
		}

		$result =
			! isset( $gglcptch_options[ $form_slug ] ) ||
            (
				! empty( $gglcptch_options[ $form_slug ] ) &&
				( ! $is_user_logged_in || ! gglcptch_is_hidden_for_role() )
			);

		return $result;
	}
}
```

Note:
- `wp_is_json_request()` will return True if `Accepts` or `Content-Type` headers contain `application/json`.
- Whenever you update the reCaptcha plugin, you have to re-edit the plugin file.
