### ISSUE TITLE
Able to get response without providing tokens

### ISSUE THREAD

**Issue by hartantothio** [Tmeister/wp-api-jwt-auth#169]
After installing the plugin and went through all the setup, I'm able to still see the response in /wp-json entry point. I think I found out what the issue is:

My test case is: when the variables `$_SERVER['HTTP_AUTHORIZATION']` and `$_SERVER['REDIRECT_HTTP_AUTHORIZATION']` is an empty string, I get the response from the entrypoints without providing any tokens.

I think the issue is when the following happens:
https://github.com/Tmeister/wp-api-jwt-auth/blob/develop/public/class-jwt-auth-public.php#L237-L243

we're not setting the `jwt_error` in this line:
https://github.com/Tmeister/wp-api-jwt-auth/blob/develop/public/class-jwt-auth-public.php#L203

Is this expected?

**Comment by vella-nicholas** [comment]
I am having the same issue. If I do not set the Authorization header, I am able to get the response normally.

**Comment by hartantothio** [comment]
In case of interest, you can replace this part of the code: https://github.com/Tmeister/wp-api-jwt-auth/blob/develop/public/class-jwt-auth-public.php#L202-L210

with the following snipet (it can probably be cleaner).

```
if (is_wp_error($token)) {
    if ($token->get_error_code() === 'jwt_auth_no_auth_header') {
        if ($_SERVER['REQUEST_URI'] !== '/wp-json/jwt-auth/v1/token') {
            /** If there is a error, store it to show it after see rest_pre_dispatch */
            $this->jwt_error = $token;
        }
    } else {
        /** If there is a error, store it to show it after see rest_pre_dispatch */
        $this->jwt_error = $token;
    }

    return $user;
}
```
