### ISSUE TITLE
Every endpoint works except wp-json/jwt/v1/token (404 - No route was found matching the URL and request method)

### ISSUE THREAD

**Issue by Steffi3rd** [Tmeister/wp-api-jwt-auth#172]
Hello guys, 

I'm using this plugin for a while in development, but now I'm in production and it doesn't work. 

Every endpoint works except this : `wp-json/jwt/v1/token`

- [x] `wp-json` OK
- [x] `wp-json/jwt/v1` OK
- [ ] `wp-json/jwt/v1/token` NOK
- [x] `wp-json/myApp/v2` OK
- [x] `wp-json/myApp/v2/*` OK

I have this response : 
```
{"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}
```

My htaccess is already set up

```
# BEGIN JWT
RewriteEngine on
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
# END JWT

# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
# END WordPress
```

I also add my `JWT_AUTH_SECRET_KEY`

```
define('JWT_AUTH_SECRET_KEY', 'your-top-secrect-key');
```

What else can I do to fix this please?

**Comment by Windygo** [comment]
Having exact same issue. /token endpoint returns 

{
    "code": "rest_no_route",
    "message": "No route was found matching the URL and request method",
    "data": {
        "status": 404
    }
}

**Comment by kdpuvvadi** [comment]
Same error Here mate, any solution as of now?

**Comment by dub34** [comment]
Hi. Try this POST wp-json/jwt-auth/v1/token. Version 1.2.6, 

You can call wp-json/ and in the response you can found all available namespaces. Hope it can help

**Comment by pravinfullstack** [comment]
Try disabling and reinstall plugin.

**Comment by adamgen** [comment]
I had this issue when sending `GET` requests, sending `POST` resolved it for me.

**Comment by irzhywau** [comment]
> Try disabling and reinstall plugin.

@power-cut which plugin are you talking about here?

I'm still facing this issue now and apparently it only occurs on `POST /wp-json/jwt-auth/v1/token`

**Comment by AntonERG** [comment]
Same issue here, any solution?

**Comment by anwarr1** [comment]
Same issue here, any solution?

**Comment by mian678** [comment]
Same issue here, Any solution?

I am trying POST request, but still getting the same error

**Comment by vagkalosynakis** [comment]
I was struggling for a while with this and even though I was using `POST` to make the request I was still having issues.

What solved it for me is having to write `https://` before my URL. Previously I was using the URL only and I was getting `rest_no_route` while I had written the `.htaccess` rules according to the documentation and also restart my server.

**Comment by LordSimal** [comment]
Also make sure you specify the URL correctly (see output of /wp-json for all valid JSON URLs)

So I tried https://mydomain.com/wp-json/jwt-auth/v1/token but instead I had to use https://www.mydomain.com/wp-json/jwt-auth/v1/token (notice the added `www.` at the start)

**Comment by tkreuder** [comment]
@LordSimal thanks a lot. That also fixed it for me!

**Comment by SFTecnologia2018** [comment]
boa noite, para mim o erro era um espaço  a mais no final da URL ("/wp-json/jwt-auth/v1/token ") de token removi o espaço e funcionou, outra coisa que fiz mas não sei se fez diferença, foi fazer as configurações primeiro e depois ativar o plugin, na alteração do .htaccess fiz em 2 arquivos, na pasta "public_html" na raiz de todos os domínios e no .htaccess no domínio da API.
estou usando Hostgator com múltiplos domínios
