### ISSUE TITLE
Update this Plugin?

### ISSUE THREAD

**Issue by ivanjeremic** [Tmeister/wp-api-jwt-auth#174]
I'm confused since last commit was 2 months ago and in the plugin library of wp it says 7 months ago, is this still up to date and a safe to use and maintaned plugin?

**Comment by raphaelnikson** [comment]
tbm queriar saber.

**Comment by s4m0r4m4** [comment]
@Tmeister - I have the same concern. Is this plugin still maintained? I'm on Wordpress 5.6 and I get the following warning when installing this plugin: "`Warning: This plugin has not been tested with your current version of WordPress.`" Authentication is a very serious topic and if this plugin is no longer maintained, then this should be noted in the README of this github repo so folks know.

**Comment by pesseba** [comment]
I'm using this plugin too and I'm a collaborator. I pretend to keep this plugin functional and working. I'm using the plugin in wordpress 5.6.1 and it's fine.
Authentication is a very serious topic, but there is no serious changing in wordpress updates a long time ago... The last one auth updates was REST API authentication with Application Passwords at [5.6 Simone](https://wordpress.org/news/2020/12/simone/). Just another way to auth the wp like this plugin does.

**Comment by s4m0r4m4** [comment]
Thanks for the quick reply! Glad to hear this is still maintained. Can you update the plugin in the WordPress ecosystem to show that it's been tested up through 5.6.1? Not sure how to do that, otherwise I'd submit a PR myself. I think that would be immensely helpful for users to know that.

**Comment by Tmeister** [comment]
I just update the "Tested up to:" version, here and in the WordPress SVN repo.

**Comment by s4m0r4m4** [comment]
Thanks!
