### ISSUE TITLE
is_user_logged_in()

### ISSUE THREAD

**Issue by worker1024** [Tmeister/wp-api-jwt-auth#175]
After installing the plugin, I can't judge the login by is_user_logged_in(). What function should I use?

**Comment by ivanjeremic** [comment]
The guy who made this plugin doesen't care anymore...I think he lost his GitHub credentials....I hope someone with passion and time will fork this plugin and update it more often and ads features!

**Comment by contactjavas** [comment]
Hey @ivanjeremic , i made [jwt-auth plugin](https://wordpress.org/plugins/jwt-auth/) based on this plugin and it solves issue #169 and #187 plus some modifications on the response (using WP_REST_Response instead of WP_Error).

I hope it can be useful for people.
