### ISSUE TITLE
Authorization header was not found.

### ISSUE THREAD

**Issue by digitxo** [Tmeister/wp-api-jwt-auth#182]
Hi. I'm doing a request to https://mywebsite.com/wp-json/jwt-auth/v1/token and I get this error when I put the username and password as form-fields in the POST.

{
    "code": "rest_authentication_no_header",
    "message": "Authorization header was not found.",
    "data": {
        "status": 403
    }
}

That's my response!

**Comment by ajoslin103** [comment]
You might be misconfigured on the server side

The Postman app helped me to figure out the problems I was having, it returns more information than what the browser gave me

These were my additions to the .htaccess & wp-config files

.htaccess 

```
# BEGIN Federated Login Support - via: JWT Authentication for WP-API (plugin) 
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
<IfModule mod_rewrite.c>
RewriteEngine on
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
</IfModule>
# END Federated Login Support - via: JWT Authentication for WP-API (plugin) 

```
wp-config.php

```
# BEGIN Federated Login Support - via: JWT Authentication for WP-API (plugin) 
define( 'JWT_AUTH_SECRET_KEY',   '95hdjnyzllfet [...] pqxzbqmw' );
define( 'JWT_AUTH_CORS_ENABLE',  true );
# END Federated Login Support - via: JWT Authentication for WP-API (plugin) 

```

Cheers,
Al;

**Comment by SabrinaDanielle** [comment]
I need to add the lines above, but the code in the .htaccess file says to use a wp filter:

```
# BEGIN WordPress
# The directives (lines) between `BEGIN WordPress` and `END WordPress` are
# dynamically generated, and should only be modified via WordPress filters.
# Any changes to the directives between these markers will be overwritten.
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress
```

any advice would be appreciated. A hook is provided: jwt_auth_cors_allow_headers but...
