### ISSUE TITLE
Support for WordPress Multisite?

### ISSUE THREAD

**Issue by Mulli** [Tmeister/wp-api-jwt-auth#184]
I have a working version on single site.

The access to the main site in WP multisite is OK,
but I get refusal on other sites in my WP multisite.
```
..."jwt_auth_bad_iss","message":"The iss do not match with this server" ...
```
I have chekced the user name & passwords – they are OK.
Using: wp-api-jwt-auth version 1.2.6
and WordPress (multisite ) 5.3.2
Any help, idea is appreciated

Thanks

**Comment by Richi2293** [comment]
Nobody answering? Is this plugin not maintained at all?
(it seems to work for me, but it would be interesting to understand if can keep a nice project like this up to date)

**Comment by contactjavas** [comment]
Hi @Mulli , It seems like an issue with multisite. Maybe adjustment is needed on the `$token->iss` checking.

Hi @Richi2293 , this plugin is great and has a lot of install. I build [jwt-auth](https://wordpress.org/plugins/jwt-auth/) based on this plugin to match my need and keeping it up to date.
