### ISSUE TITLE
Didn't restrict another Api with JWT auth plugin.

### ISSUE THREAD

**Issue by jenthakkar** [Tmeister/wp-api-jwt-auth#187]
FYI: I have a Woocommrce backend Website and ios frontend. I'm working with Rest API only.Also, Can JWT Auth restrict woocommerce too?

I'm using JWT authentication Plugin for Authentication and Login Api And Token https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/. 

complete all requirements which plugin needs like edit .htaccess, .wp-config.php and also clone wp-rest-api plugin. but this plugin didn't restrict any rest API like localhost/wp-json or create post API. I used all solutions of link https://github.com/WP-API/Basic-Auth/issues/35.also download basic Auth Plugin.

All API works fine as it worked and also I can create token and login via JWT auth. but I want to restrict my all API with JWT auth.

**Comment by zclmoon** [comment]
I got the same issue, the apis still work after enable the plugin.
Hi @jenthakkar  did you figure out the issue?

**Comment by zclmoon** [comment]
@jenthakkar  you may can refer to https://github.com/Tmeister/wp-api-jwt-auth/issues/169
