### ISSUE TITLE
user role auth?

### ISSUE THREAD

**Issue by paOol** [Tmeister/wp-api-jwt-auth#19]
so this is a successful response

```
{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9qd3QuZGV2IiwiaWF0IjoxNDM4NTcxMDUwLCJuYmYiOjE0Mzg1NzEwNTAsImV4cCI6MTQzOTE3NTg1MCwiZGF0YSI6eyJ1c2VyIjp7ImlkIjoiMSJ9fX0.YNe6AyWW4B7ZwfFE5wJ0O6qQ8QFcYizimDmBy6hCH_8",
    "user_display_name": "admin",
    "user_email": "admin@localhost.dev",
    "user_nicename": "admin"
}
```

is there a way to get the user's role as well?
Let's say I'm an admin and want to have a page that only admins can see.
Currently, I don't know of a way to limit a regular member from accessing that admin-only page.

**Comment by MurhafSousli** [comment]
you are looking for this hook **jwt_auth_token_before_dispatch**

The `jwt_auth_token_before_dispatch` allows you to modify all the response array before to dispatch it to the client.

Add this to your `functions.php`

```
<?php
function jwt_auth_function($data, $user) {
    $data['user_role'] = $user->roles;
    return $data;
}
add_filter( 'jwt_auth_token_before_dispatch', 'jwt_auth_function', 10, 2 );
?>
```
