### ISSUE TITLE
Can't access wp-configure PHP with a business WordPress template account

### ISSUE THREAD

**Issue by Supersketch** [Tmeister/wp-api-jwt-auth#190]
I have done everything I want with a WordPress business account and template which means I don't generally write code from scratch for my blog. Instead I tend to adjust settings to get the results.

I want to make my Wordpress blog which is a magazine into an app. I found AppPresser but the problem with creating the app seems to be that I cannot configure the secret key for the installation. 

Can anyone help me please.

**Comment by pesseba** [comment]
I believe if you can define the JWT_AUTH_SECRET_KEY anywhere, and the plugin still works. It just need to be in a script called in every call.

**Comment by Supersketch** [comment]
I'm still trying to work through this with the WordPress.com site not allowing users to easily access the Wp-configure.php it's looking like I'll need to use FileZilla to prise open the back end of WordPress fenced off for those on template versions.

**Comment by pesseba** [comment]
You still need to edit .htaccess file to make the jwt plugin to work, not only wp-config. 
I create this simple plugin, that you can extract, edit the values (create your key), zip to upload in your site, and activate it.
[jwt-define.zip](https://github.com/Tmeister/wp-api-jwt-auth/files/4404874/jwt-define.zip)

**Comment by Supersketch** [comment]
Thank you, really an encouragement to have your help working on this pesseba.

**Comment by Supersketch** [comment]
Anyone else want to participate in this hack?
