### ISSUE TITLE
add_filter('jwt_auth_token_before_sign') cause Warning: Use of undefined constant extend_token_expiration - assumed 'extend_token_expiration'

### ISSUE THREAD

**Issue by Steffi3rd** [Tmeister/wp-api-jwt-auth#191]
Hello, 

I have this warning/error 

> Warning: Use of undefined constant extend_token_expiration - assumed 'extend_token_expiration' (this will throw an Error in a future version of PHP) in /Users/bookie/Local Sites/app/public/wp-content/plugins/abc/myapp.php on line 1346

And 

> Cette extension a généré 1945 caractères de sortie inattendus lors de son activation. Si vous remarquez des messages « headers already sent », des problèmes avec vos flux de syndication ou d’autres soucis, essayez de désactiver ou de supprimer cette extension.

When I add this in my plugin `myapp.php`

```
add_filter('jwt_auth_token_before_sign', extend_token_expiration, 10, 2);
function extend_token_expiration($token, $user) {
  $token['exp'] = time() + MONTH_IN_SECONDS; 
  return $token;
}
```

What's wrong?

--- 
Wordpress: 5.3.2
PHP: 7.3.5
MySQL : 8.0.16

**Comment by pesseba** [comment]
You used a function directly in hook. You should use a string instead.:

`add_filter('jwt_auth_token_before_sign', 'extend_token_expiration', 10, 2);`

**Comment by Steffi3rd** [comment]
@pesseba Damn... I didn't noticed it. 

So you are telling me that line never worked? 😂

(It's first time I saw this error and in old environnement it uses this same line, but never warn anything...)

**Comment by Steffi3rd** [comment]
@pesseba Perfect, it works great! Thank you very much.
