### ISSUE TITLE
[Feature Request] ability to customize authorization header

### ISSUE THREAD

**Issue by ricokahler** [Tmeister/wp-api-jwt-auth#195]
We use HTTP basic auth in our dev environments to protect it from search engines etc. This is an issue because basic auth header collides with the `Authorization: Bearer` header.

Some other JWT plugins, solved this by adding in [a filter to allow changing the header](https://github.com/wp-graphql/wp-graphql-jwt-authentication/blob/d0faaab6cc0dfba47cf111613ad665e7c465e2ff/src/Auth.php#L647). If I get your blessing, I'd be happy to add this feature.

Thank you!

**Comment by sviluppomania** [comment]
Hi @ricokahler , I think you should include it. I have enclosed all the changes in a single pull called: version. 1.2.7, you can start with the one not to be missed.

**Comment by ricokahler** [comment]
@sviluppomania I'm confused on what your status is on this repo. Are you a maintainer and can you merge PRs?

**Comment by sviluppomania** [comment]
@ricokahler to simplify, I tested and then joined all the pulls present in a single pull called "Version 1.2.7", if you want to make changes, start with that too.  Do not miss anything.

**Comment by ricokahler** [comment]
@sviluppomania I'm still confused. You have 4 pulls open (not one) on this repo, you do not appear as a maintainer, and version 1.2.7 doesn't seem like the correct semver version for this feature.

**Comment by sviluppomania** [comment]
@ricokahler Simply because I am one like many others who make proposals. Version 1.2.7 is a proposal. If you want to follow the advice do not miss the changes. If you don't want to follow the advice, patience. :)
