### ISSUE TITLE
Notice: register_rest_route was called incorrectly.

### ISSUE THREAD

**Issue by rajweb** [Tmeister/wp-api-jwt-auth#207]
Wordpress Version: 5.5
WooCommerce Version: 4.3.3

i got below notic in **woocommerce section** of admin panel:

1- Notice: register_rest_route was called incorrectly. The REST API route definition for jwt-auth/v1/token is missing the required permission_callback argument. For REST API routes that are intended to be public, use __return_true as the permission callback. Please see Debugging in WordPress for more information. (This message was added in version 5.5.0.) in /home/rajkamal/public_html/test_wp/wp-includes/functions.php on line 5225.

2- Notice: register_rest_route was called incorrectly. The REST API route definition for jwt-auth/v1/token/validate is missing the required permission_callback argument. For REST API routes that are intended to be public, use __return_true as the permission callback. Please see Debugging in WordPress for more information. (This message was added in version 5.5.0.) in /home/rajkamal/public_html/test_wp/wp-includes/functions.php on line 5225

thanks in advance

**Comment by mvdhoek1** [comment]
I was trying to open a pull-request but obviously I do not have the correct access rights.

Below should do the trick

```
    /**
     * Add the endpoints to the API
     */
    public function add_api_routes()
    {
        register_rest_route($this->namespace, 'token', array(
            'methods' => 'POST',
            'callback' => array($this, 'generate_token'),
            'permission_callback' => __return_true(),
        ));

        register_rest_route($this->namespace, 'token/validate', array(
            'methods' => 'POST',
            'callback' => array($this, 'validate_token'),
            'permission_callback' => __return_true(),
        ));
    } 
```

**Comment by simplenotezy** [comment]
Created a pull request here: https://github.com/Tmeister/wp-api-jwt-auth/pull/209

**Comment by velara3** [comment]
Was receiving the same error. Some general advice. 

Should I add this to my plugin directly or wait until a release? If I add it (for now) will it be ok when a new release containing this change is out and that update will overwrite it (or cause update errors)?

**Comment by jnz31** [comment]
> Was receiving the same error. Some general advice.
> 
> Should I add this to my plugin directly or wait until a release? If I add it (for now) will it be ok when a new release containing this change is out and that update will overwrite it (or cause update errors)?

you can add it manually. on plugin update, this would be overwritten.

**Comment by pondermatic** [comment]
According to [REST API changes in WordPress 5.5](https://make.wordpress.org/core/2020/07/22/rest-api-changes-in-wordpress-5-5/#callback), pull request #209 fixes this issue correctly.

**Comment by rponline** [comment]
Just got the same error and can confirm that PR #209 fixes the issue.
I would love to see it in the next update!

**Comment by hideki-masuoka** [comment]
Hope! next version.
I created a fix plugin while waiting for the next version. (Google translate)
[GitHub - hideki-masuoka/quiet-wp-api-jwt-auth: Fix > Notice: register_rest_route was called incorrectly. #207](https://github.com/hideki-masuoka/quiet-wp-api-jwt-auth)

**Comment by pglewis** [comment]
This was reported over a year ago, it's a very simple fix, and even has a proper PR #209.  Is there a reason for the hold up?

**Comment by vncafecode** [comment]
It's December 2021 and the PR is still in review? I have the same issue and have to manually edit the plugin files.

**Comment by lkraav** [comment]
It's increasingly looking like this code is abandonware :( Is anyone here aware of any current alternatives?

**Comment by lkraav** [comment]
What about https://github.com/usefulteam/jwt-auth which seems to be adequately maintained.
