### ISSUE TITLE
Can't change JWT_AUTH_SECRET_KEY value from "your-top-secret-key" to others

### ISSUE THREAD

**Issue by davidekingsss** [Tmeister/wp-api-jwt-auth#217]
I got "Signature verification failed" error when I tried to change "your-top-secret-key" into another value. 

`{"code":"jwt_auth_invalid_token","message":"Signature verification failed","data":{"status":403}}`

I reboot server but not working. Everything  goes well when I change it back to default. How can I fix it?

**Comment by pesseba** [comment]
If you change the secret, all tokens become invalid. It's working properly....
