### ISSUE TITLE
V2 or V1 ?

### ISSUE THREAD

**Issue by onigetoc** [Tmeister/wp-api-jwt-auth#23]
It say, this is for WP API V2 but all your examples are url based on the V1 api 
It's seem to not work with: https://wordpress.org/plugins/rest-api/

`/wp-json/jwt-auth/v1/token`
or

```
http://yourdomain.com/wp-json';
    $http.post( apiHost + '/jwt-auth/v1/token

```

**Comment by Tmeister** [comment]
The plugin version is 1 `/jwt-auth/v1/token` this version has nothing to do with the rest-api version which is 2.0

Here is the namespace definition for the plugin https://github.com/Tmeister/wp-api-jwt-auth/blob/develop/public/class-jwt-auth-public.php#L67
