### ISSUE TITLE
Can you add an option to get the user id when we get jwt token

### ISSUE THREAD

**Issue by elmcapp** [Tmeister/wp-api-jwt-auth#231]
If we run a post request to generate token we get the follow: (/wp-json/jwt-auth/v1/token)
1. token
2. user email
3. user nicename
4. user display name

Can you please also provide the ID.  
When I look in the class file I found the follow

            'token' => $token,
            'user_email' => $user->data->user_email,
            'user_nicename' => $user->data->user_nicename,
            'user_display_name' => $user->data->display_name,

I was able to add 'user_id' => $user->data->ID.    

The problem is that every time the plugin updates or I reinstall the plugin I have to keep adding the line of code. Can you please add it in permanently

**Comment by Tmeister** [comment]
You can add more information on the response using the `jwt_auth_token_before_sign` [here.](https://github.com/Tmeister/wp-api-jwt-auth/blob/develop/public/class-jwt-auth-public.php#L170)
