### ISSUE TITLE
UI in admin area to whitelist endpoints

### ISSUE THREAD

**Issue by contactjavas** [Tmeister/wp-api-jwt-auth#232]
Hi Guys, is it a good idea to have a UI in the admin area to allow people to whitelist some endpoints / maybe modify the default whitelisted endpoints?

Sure, we have some filters. But seems like it's quite often people come with issues like "x or y or z" plugins don't work (due to blocked request).
And then we suggest using a filter to solve that, and then they ask where to put the codes.

Not sure if an options page in the admin area is necessary, but what do you think?

**Comment by ThienTranDuy** [comment]
Do you find a solution for this one?
