### ISSUE TITLE
will the plugin be updated?

### ISSUE THREAD

**Issue by Matteo182** [Tmeister/wp-api-jwt-auth#233]
Hi I noticed that the plugin has not been updated for more than a year, I wanted to know if you will update it again and therefore if the plugin is still alive or not. I should be using it in a major project and I wanted to know just to be safe. A thousand thanks

**Comment by pesseba** [comment]
Try this other plugin based on this (it's better maintened): https://wordpress.org/plugins/jwt-auth/

**Comment by Matteo182** [comment]
many thanks, the plugin looks the same so i guess just replace it, the changes made in the config.php and htaccess are the same.

**Comment by souleater2023** [comment]
> many thanks, the plugin looks the same so i guess just replace it, the changes made in the config.php and htaccess are the same.

does it work?

**Comment by Matteo182** [comment]
Yes, it works correctly. I recommend it
