### ISSUE TITLE
generated token is not working

### ISSUE THREAD

**Issue by MurhafSousli** [Tmeister/wp-api-jwt-auth#24]
Hi,
I got this problem after I get my token, It never works for Authorization in POST or GET, I always get this:

![Image of Yaktocat](https://s23.postimg.org/xqu5ib81n/401.jpg)

Did I miss anything in the header?

**Comment by Tmeister** [comment]
This should be solved with https://github.com/Tmeister/wp-api-jwt-auth/commit/d7bfd793c9ce52bb3b158adff4cc11656c366027
