### ISSUE TITLE
Response Header  without Content-Type

### ISSUE THREAD

**Issue by Odyno** [Tmeister/wp-api-jwt-auth#25]
Hi, 
I have done one Angulajs example but I have this error:

XMLHttpRequest cannot load http://blablabla.lan/wp-json/jwt-auth/v1/token. Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.

This is my Response Header when I take one token

HTTP/1.1 200 OK
Date: Sat, 04 Jun 2016 08:24:40 GMT
Server: Apache
X-Powered-By: PHP/5.4.45
Access-Control-Allow-Headers: Authorization
X-Content-Type-Options: nosniff
Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages
Allow: POST
Content-Length: 329
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: application/json; charset=UTF-8

and the  *\* Access-Control-Allow-Headers: Authorization *\* is only _Authorization_ without _Content-Type_. 

In the code at https://github.com/Tmeister/wp-api-jwt-auth/blob/master/public/class-jwt-auth-public.php#L93 is added the content type, but some other stuff rewrite it.

My configuration:
- vccw machine
- Wordpress 4.5.2
- Akismet Version 3.1.11 | By Automattic | View details
- Dynamic Hostname Version 0.4.2 | By Takayuki Miyauchi | View details
- Hello Dolly Version 1.6 | By Matt Mullenweg | View details
- JWT Authentication for WP-API Version 1.2.0 | By Enrique Chavez | View details
- TinyMCE Templates Version 4.4.3 | By Takayuki Miyauchi | View details
- WP REST API Version 2.0-beta13.1 | By WP REST API Team | View details
- WP Total Hacks Version 2.0.1 | By Takayuki Miyauchi | View details

**Comment by simonh1000** [comment]
I have submitted a patch to get CORS working

**Comment by Mulli** [comment]
Not working for me...
Wordpress 5.1.1
JWT Authentication for WP-API Version 1.2.6 | By Enrique Chavez | View details
No WP-API plugin
