### ISSUE TITLE
Delete Endpoint Not Working for User ID

### ISSUE THREAD

**Issue by FinalGale** [Tmeister/wp-api-jwt-auth#279]
Getting a 405 Not Allowed response when making a DELETE request for a specific user id. 
I am trying to use this DELETE method below.
<img width="246" alt="image" src="https://github.com/Tmeister/wp-api-jwt-auth/assets/46613691/0b0045ce-06ea-4e61-8276-36180d504f22">
<img width="636" alt="image" src="https://github.com/Tmeister/wp-api-jwt-auth/assets/46613691/8f417a1c-d821-4685-8363-82e2a79cb0c7">

**Comment by Tmeister** [comment]
Please.

Can you give more details, like what plugins are installed, exactly what method you are consuming, and the user role is making the request, etc.?

It's hard for me to guess.
