### ISSUE TITLE
JWT auth failed

### ISSUE THREAD

**Issue by simonpeters** [Tmeister/wp-api-jwt-auth#29]
I always get invalid credentials error. I tried with the admin account and also with new users and always the same error.

`{"code":"jwt_auth_failed","message":"Invalid Credentials.","data":{"status":403}}
`

Anyone here know how to solve this?

**Comment by apieum** [comment]
Hi, I have the same issue and found why this happens. 
In my case it's because php is in CGI mode and var `$_SERVER['HTTP_AUTHORIZATION']` is replaced by `$_SERVER['REDIRECT_HTTP_AUTHORIZATION']`

**Comment by Tmeister** [comment]
Now the plugin returns the exact error sent by WordPress, WordPress validate if the user/pass are correct, see the follow commit https://github.com/Tmeister/wp-api-jwt-auth/pull/40/commits/f197cda513a278bdfcccff86c87ead4364db7ca5
