### ISSUE TITLE
jwt_auth_bad_auth_header

### ISSUE THREAD

**Issue by PyNApo** [Tmeister/wp-api-jwt-auth#3]
Hello,

Thanks for your plugin.

When i try your sample request with angular i've this response: 
    "code": "jwt_auth_bad_auth_header",
    "message": "Authorization header malformed.",
    "data": {
      "status": 403
    }

What's wrong ?

**Comment by PyNApo** [comment]
How can I control the header ?

**Comment by Tmeister** [comment]
You need to be sure you send the proper token along the header

```js
app.config( function( $httpProvider ) {
  $httpProvider.interceptors.push( [ '$q', '$location', '$cookies', function( $q, $location, $cookies ) {
    return {
      'request': function( config ) {
        config.headers = config.headers || {};
        //Assume that you store the token in a cookie.
        var globals = $cookies.getObject( 'globals' ) || {};
        //If the cookie has the CurrentUser and the token
        //add the Authorization header in each request
        if ( globals.currentUser && globals.currentUser.token ) {
          config.headers.Authorization = 'Bearer ' + globals.currentUser.token;
        }
        return config;
      }
    };
  } ] );
} );
```

You need to verify the content in this line

```js
config.headers.Authorization = 'Bearer ' + globals.currentUser.token;
```

In this example i asume that you are using cookies to store the token.

**Comment by PyNApo** [comment]
OK. Thanks.
How can i store token in a cookie ?

**Comment by PyNApo** [comment]
Thanks.

I know how to create a cookie with angularjs but how can i store the token in ?

**Comment by PyNApo** [comment]
Thanks for your reply.
I'm new with WP REST API and authentication... sorry...

I don't know what to do ?
"//Assume that you store the token in a cookie.
var globals = $cookies.getObject( 'globals' ) || {};"

**Comment by PyNApo** [comment]
I need to create POST with angularjs + WP REST API

**Comment by Tmeister** [comment]
I'm sorry but this is not the place to ask how to store a cookie or how to consume the REST API

This plugin only give you the ability to sign a request and authenticate the user using the JWT token.

You can find more information on how to use the WP REST API in the [documentation site](http://v2.wp-api.org/)

**Comment by PyNApo** [comment]
OK Sorry.
I found another solution.

**Comment by h3ndro** [comment]
hi PyNApo, would you share your solution?i'm facing the same problem

**Comment by h3ndro** [comment]
nevermind,..i got it working

**Comment by medrockstar** [comment]
hi,

I have the same problem with Postman in my local server.

Tks,

**Comment by sirdowan** [comment]
@h3ndro @PyNApo  and what was your solution?? screenshot of Postman or something? 
Thanks!
