### ISSUE TITLE
404 on page

### ISSUE THREAD

**Issue by araratmartirossyan** [Tmeister/wp-api-jwt-auth#31]
Hello guys i have a problem with plugin. When i use this link wp-json/jwt-auth/v1/token they show me 
`{
code: "rest_no_route",
message: "No route was found matching the URL and request method",
data: {
status: 404
}
}`

When i try to post with angular console show me 

`XMLHttpRequest cannot load http://mysite.me/wp-json/jwt-auth/v1/token. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access.`
i add this to my wp-config.php 

```

define('JWT_AUTH_CORS_ENABLE', true);
define('JWT_AUTH_SECRET_KEY', 'ZJ_){TkyM{Eo$R<n?f-oJ}z2!6i0MZ~XPm<ij$2T/bY=XtUU8|x!EWi]+`nPf^Q&');
```

and this is my httacess 

```
<ifModule mod_headers.c>
    Header always set Access-Control-Allow-Origin: "*"
    Header always set Access-Control-Allow-Methods "POST, GET, PUT, DELETE, OPTIONS"
    Header always set Access-Control-Allow-Headers "Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With"
</ifModule>
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress

```

What a problem? Why i have 404?

**Comment by araratmartirossyan** [comment]
any support?

**Comment by lucianomlima** [comment]
Have this problem too. Local working fine with PHP 7.0 and Apache, but in production with Nginx and PHP 7.0 always return 404 for POST requests on `wp-json/jwt-auth/v1/token`.

Were you able to solve this?

**Comment by tpresing** [comment]
On Nginx i also have the same issue :( Any solutions?

**Comment by toddzebert** [comment]
it's `add` not `set`, like:

```
Header add Access-Control-Allow-Origin "*"
Header add Access-Control-Allow-Headers "origin, x-requested-with, content-type"
Header add Access-Control-Allow-Methods "PUT, GET, POST, DELETE, OPTIONS"
```

**Comment by lucianomlima** [comment]
@toddzebert this is for Apache. Any ideas for Nginx?

**Comment by ModPilot** [comment]
bummer.  I'm using NGINX too - same 404 error... no solves, eh?

**Comment by licdream** [comment]
the same error in Nginx.

**Comment by licdream** [comment]
Seems we`ve all made a mistake. Nginx do not support the .htaccess file. :( 
[https://www.nginx.com/resources/wiki/start/topics/examples/likeapache-htaccess/](https://www.nginx.com/resources/wiki/start/topics/examples/likeapache-htaccess/)

Maybe Converting the .htaccess file to nginx-conf is the solution for this issue, just like below:
[https://stackoverflow.com/questions/35766676/how-can-i-use-htaccess-file-in-nginx](https://stackoverflow.com/questions/35766676/how-can-i-use-htaccess-file-in-nginx)
[http://winginx.com/en/htaccess](http://winginx.com/en/htaccess)

But i`m a novice with nginx-conf. So, I wish you guys to show a full example of nginx-conf for JWT plugins.

**Comment by toddzebert** [comment]
I haven't used NGINX in any but trivial ways, but some Googling resulted in:

https://enable-cors.org/server_nginx.html
https://gist.github.com/Stanback/7145487
And many more...

I would start there.

**Comment by MarvinKlar** [comment]
In my case the problem was that I used an HTTP URL, but the webserver was configured to redirect HTTP to HTTPS. Changing HTTP to HTTPS in the request URL fixed the problem.

**Comment by leeci** [comment]
Add this in nginx config `server` block can solve it
```
        location ~ ^/wp-json/ {
                # if permalinks not enabled
                rewrite ^/wp-json/(.*?)$ /?rest_route=/$1 last;
        }
```
Because nginx only support `http://example.com/?rest_route=/` equal to `http://example.com/wp-json/`

**Comment by oyepez003** [comment]
Try using the **Post name** option in the Permalink Settings (Settings / Permalink)
