### ISSUE TITLE
How I use the hook jwt_auth_expire via POST

### ISSUE THREAD

**Issue by angelow373** [Tmeister/wp-api-jwt-auth#32]
Hello, I want to know how can I use the hook jwt_auth_expire to set an exp via POST.

For example, I want to send a post via Unity like this:
[...]

```
form.AddField("username", admin); // Attaching the username
form.AddField("password", password); // Attaching the password
**form.AddField("jwt_auth_expire", "20");** // Attaching the exp? How do I attach the exp for that hook to send in the POST? (20 seconds?)
data = form.data;
www = new WWW(url + requestToken, data);
```

Equals to this in the example you did:

```
$http.post( apiHost + '/jwt-auth/v1/token', {
        username: 'admin',
        password: 'password',
        jwt_auth_expire: '20' // Attaching the exp? How do I attach the exp for that hook to send in the POST? (20 seconds?)
      } )
```

[...]
I don't know if I did understand, I don't work with wordpress, so...
Thank you very much!

**Comment by pesseba** [comment]
Hello Angelo, In documentation jwt is cited as a filter. 

> ... is dev friendly and has five filters available to override the default settings.

So I believe thats works as this:

/wp-json/jwt-auth/v1/token?filter[jwt_auth_expire]=1000

**Comment by ahmu83** [comment]
How to use it in php function?

**Comment by alibasheer** [comment]
@ahmu83  you can use this hook

```// increase the token duration to expire from 7 days to 365 days
function ba_jwt_auth_expire( $issuedAt ) {
    return $issuedAt + (DAY_IN_SECONDS * 365);
}
add_filter( 'jwt_auth_expire', 'ba_jwt_auth_expire' );

**Comment by alaa-alsalehi** [comment]
does this work
/wp-json/jwt-auth/v1/token?filter[jwt_auth_expire]=1000
and how I can test it?
I tried to test it through 1 second
/wp-json/jwt-auth/v1/token?filter[jwt_auth_expire]=1
and use validate endpoint to check on it and the token take tooo much time to be invalid

**Comment by Pushkar98** [comment]
Did it worked? This thing "/wp-json/jwt-auth/v1/token?filter[jwt_auth_expire]=1000"

**Comment by captaincole** [comment]
Hey all tried a couple of things, and nothing seemed to override the filter from a post request. My example post request url looks like this.

```
https://<my-wp-url>.com/wp-json/jwt-auth/v1/token?filter[jwt_auth_expire]=<(Date.now() / 1000) + 100>
```

With username and password in the body.

The value for jwt_auth_expire filter is given in seconds since epoch plus 100 so it will expire in 100 seconds from creation, which I believe aligns with the add_filter() php function referenced above.

All tokens issued still expire in 1 week. Anybody else have this working as a post request?
