### ISSUE TITLE
idea - better response on authentication try

### ISSUE THREAD

**Issue by sissibieber** [Tmeister/wp-api-jwt-auth#34]
The plugin works great - during development we came across the issue, that we didn't know why the login wasn't working - there was always "Wrong credentials" as code, so this is just an idea...

In order to give the API the possibiltiy to know why the login (class-jwt-auth-public.php, line 122) has failed (empty password, wrong email, non exisiting user, or wrong password) it would be great to not return one text as message, but user the wp_error object and return the error codes in the API?

**Comment by Tmeister** [comment]
Error message improved
