### ISSUE TITLE
hook to destroy token

### ISSUE THREAD

**Issue by sissibieber** [Tmeister/wp-api-jwt-auth#36]
we are using the authentication for users (obviously) - after a user has "deleted" his account (in that case we change the email/username and the users role (wp role) but the token still works after those changes. is there a way to destroy a token "by hand" or any other way to make the inital token invalid?

**Comment by apieum** [comment]
hello, you have a filter to set an expiry date, I've not tried but I guess by giving a date in the past for the token, it may work.
Look at line 139 https://github.com/Tmeister/wp-api-jwt-auth/blob/develop/public/class-jwt-auth-public.php#L139

**Comment by ssuess** [comment]
I implemented this if you want to check it out [the code is here](https://github.com/ssuess/wp-api-jwt-auth).

**Comment by jacktator** [comment]
@ssuess Looks amazing! Can you send a pull request? 💃

**Comment by ssuess** [comment]
Thanks. Already did a while back.

**Comment by beatelite** [comment]
I see there are a ton of pull requests. @Tmeister Is there any reason why? Anything we can do to help?

**Comment by pnghai** [comment]
any chance that this will be merged to the official codebase, guys?

**Comment by beatelite** [comment]
Pretty sure this plugin has been abandoned. I'm going to switch to this: https://github.com/jonathan-dejong/simple-jwt-authentication/wiki/Documentation
