### ISSUE TITLE
rest_forbidden is displayed when add 'permission_callback' for each endpoint.

### ISSUE THREAD

**Issue by PhilipDing** [Tmeister/wp-api-jwt-auth#37]
When I add 'permission_callback' for each endpoint, following error message will be displayed

```
{
    "code": "rest_forbidden",
    "message": "您无权做这件事。",
    "data": {
        "status": 403
    }
}
```

But when I remove following code in default-filters.php, it works.

```
add_filter( 'determine_current_user', 'wp_validate_auth_cookie'          );
add_filter( 'determine_current_user', 'wp_validate_logged_in_cookie', 20 );
```

I find the priority for 'determine_current_user' is 99, which is greater than system, so I don't know why.

```
$this->loader->add_filter('determine_current_user', $plugin_public, 'determine_current_user', 99);
```

**Comment by wakasann** [comment]
Wordpress Code Reference [add_filter()](https://developer.wordpress.org/reference/functions/add_filter/#parameters) param `$priority` description may be help.
