### ISSUE TITLE
rest_no_route issue

### ISSUE THREAD

**Issue by otherprod** [Tmeister/wp-api-jwt-auth#42]
Hi, 

i tried to use WP JWT AUTH plugin without success. Every time i send a query to this url : 

https://www.mydomain.com/wp-json/jwt-auth/v1/token

i have a 404 error:
```
 {"code":"rest_no_route","message":"Aucun itin\u00e9raire n\u2019a \u00e9t\u00e9 trouv\u00e9 correspondant \u00e0 l\u2019URL et \u00e0 la m\u00e9thode de requ\u00eate","data":{"status":404}}
```
For info the url: 

https://www.mydomain.com/wp-json/wp/v2/posts return an empty response (the route is ok), im using the last wp api (2 beta 15)

Thank you for your help

**Comment by Tmeister** [comment]
Are you sure the Plugin is active? I can see the namespaces

This is my dev site

![](https://d3vv6lp55qjaqc.cloudfront.net/items/353i0a1a2a390x071630/Image%202016-11-29%20at%208.59.00%20AM.png?X-CloudApp-Visitor-Id=1908589&v=8ba4f80f)

**Comment by otherprod** [comment]
I just reinstalled it to try and reflush permalinks but always the same, and yes now (was not the case a few minute ago)  the plugin is activated

**Comment by otherprod** [comment]
wp-json/jwt-auth/v1 this is ok wp-json/jwt-auth/v1/token this is not ok

**Comment by otherprod** [comment]
Ok sorry work only wih post, so sorry
