### ISSUE TITLE
Max recursion error in WordPress 4.7

### ISSUE THREAD

**Issue by Shelob9** [Tmeister/wp-api-jwt-auth#44]
I am getting fatal error maximum recursion after updating to WP 4.7. Not able to debug right now, so disabled to fix. Here is my stack trace:

Stack trace: https://pastebin.com/XiGu10jC

**Comment by brunoguimaraes** [comment]
WP 4.7, Multisite install, authentication and WP-API works fine, but wp-admin throws ERR_EMPTY_RESPONSE error on Chrome.

**Comment by Shelob9** [comment]
@brunoguimaraes Do you have WP_DEBUG and WP_DEBUG_LOG on?

**Comment by faugro** [comment]
@Shelob9
After whole day get this error, my temporary fix by editing
jwt-authentication-for-wp-rest-api\public\class-jwt-auth-public.php line 227
`__('Authorization header not found.', 'wp-api-jwt-auth'),`
change to
`'Authorization header not found.',`

Hope this help

**Comment by brunoguimaraes** [comment]
@Shelob9 Yes, both options activated.

**Comment by Tmeister** [comment]
I'm digging on this, looks like the `determine_current_user` [hook](https://github.com/Tmeister/wp-api-jwt-auth/blob/develop/includes/class-jwt-auth.php#L144) is [guilty](https://github.com/Tmeister/wp-api-jwt-auth/blob/develop/public/class-jwt-auth-public.php#L176) of this, this hook should only run on the REST API requests.

**Comment by Shelob9** [comment]
@Tmeister Removing that filter while inside of the callback should (sorry, reading not testing) fix this.

**Comment by Tmeister** [comment]
I just push a new version (1.2.3) in WP.org, and here with the fix, all my local tests work good, and the recursion error is fixed!

Please verify on your end and let me know if you see anything odd.

Will left this open a couple of days to see if something came off.

**Comment by brunoguimaraes** [comment]
@Tmeister This update fixes my issue, thank you!

**Comment by Shelob9** [comment]
Working for me too now. Thanks for the fix!

**Comment by Tmeister** [comment]
I think we can close this.

**Comment by Shelob9** [comment]
Strong agreement. Thanks for the great plugin.
