### ISSUE TITLE
Persistent login

### ISSUE THREAD

**Issue by lastant** [Tmeister/wp-api-jwt-auth#45]
Is there a good mechanism for being logged in with JWT for a long time, e.g. on the mobile devices?

**Comment by Tmeister** [comment]
You can set the expire date to whatever you want using the [jwt_auth_expire](https://github.com/Tmeister/wp-api-jwt-auth/blob/develop/public/class-jwt-auth-public.php#L139) filter, with that you can set the expiry date to 10 years for example and the token will be valid for all that time.

**Comment by lastant** [comment]
The only downside is probably that if the phone is lost or password changed, there is no way to revoke the token, or? Maybe it's possible to mix the password into the token somehow, so that the token becomes invalid when the password changes?

**Comment by Tmeister** [comment]
Yes, that's a concern, I've been thinking in add a token manager, a UI in the admin to see all the generated tokens with the revoking, deletion abilities in order to know:

1) Users using tokens (Devices and other data)
2) How many tokens exists
3) Automatically revoke all tokens on password change
4) and revoke manually.

**Comment by erikandershed** [comment]
I can't get this to work. I use this filter to change the expire date but what ever I set the time to it has no effect. In this I set it to 60 sec.

```
function filter_jwt_auth_expire( $issuedAt ) {
    return $issuedAt + (60);
}
add_filter( 'jwt_auth_expire', 'filter_jwt_auth_expire' );
```

Please help

**Comment by lastant** [comment]
@erikandershed the $issuedAt should be the second argument; the first argument is the default value ($issuedAt + (DAY_IN_SECONDS * 7)). So it should be `filter_jwt_auth_expire( $value, $issuedAt )`

**Comment by erikandershed** [comment]
This is working for me:

```
function filter_jwt_auth_expire() {
    return time() + (86400 * 365); // Days in sec * 365 days
}
add_filter( 'jwt_auth_expire', 'filter_jwt_auth_expire' );
```

**Comment by erikandershed** [comment]
Sorry.. but it do not work. When I check if I where loged in today 3 days later, I need to login agin. 

Please help!

**Comment by lastant** [comment]
First check if the function is executed at all, for example calling error_log(...). And don't forget you can debug PHP like other languages, for instance using Xdebug.

**Comment by captaincole** [comment]
Any thoughts on how this might be implemented via the REST Api. For example, 

```https://<wp-site>.com/wp-json/jwt-auth/v1/token?filter[jwt_auth_expire]=<Date in seconds>```

has consistently produced a token that expires in one week.

Any thoughts on being able to add a filter like this?

**Comment by claytoncollie** [comment]
> You can set the expire date to whatever you want using the [jwt_auth_expire](https://github.com/Tmeister/wp-api-jwt-auth/blob/develop/public/class-jwt-auth-public.php#L139) filter, with that you can set the expiry date to 10 years for example and the token will be valid for all that time.

I have a filter setup but it is after the token has already expired. Do you keep a log of expired tokens? Do I ned to create another token even if I have the filter in place?

```
add_filter( 'jwt_auth_expire', 'json_web_token_do_not_expire', 10, 2 );
/**
 * Filter the expiration time to stretch it out to 10 years.
 *
 * @param string $expire
 * @param string $issuedAt
 * @return string
 */
function json_web_token_do_not_expire( $expire, $issuedAt ) {
    
    $expire = $issuedAt + ( 10 * YEAR_IN_SECONDS );
    
    return $expire;

}
```
