### ISSUE TITLE
Plugin interferes with Woocommerce Authentication

### ISSUE THREAD

**Issue by DiarmuidByrne** [Tmeister/wp-api-jwt-auth#48]
Since I have installed the JWT plugin, it now authenticates using the wp-rest API perfectly. However my application also consumes the Woocommerce API to get product information. I was previously using basic auth for Woocommerce for development purposes but now I get a 403: "jwt_auth_bad_auth_header" when I try using basic auth. Using the generated token to authenticate also doesn't work with Woocommerce as I get a 403: "woocommerce_rest_cannot_view".

**Comment by mshick** [comment]
@DiarmuidByrne what was your solution? I'm experiencing similar problems — JWT seems to hijack all basic auth.

**Comment by zainulabidin302** [comment]
Because woommerce already uses its way of authentication, 
I have changed this:
wp-content/plugins/jwt-authentication-for-wp-rest-api/includes/class-jwt-auth.php
comment two lines in here
 
```
   private function define_public_hooks()
    {
        $plugin_public = new Jwt_Auth_Public($this->get_plugin_name(), $this->get_version());
        $this->loader->add_action('rest_api_init', $plugin_public, 'add_api_routes');
        $this->loader->add_filter('rest_api_init', $plugin_public, 'add_cors_support');
        //$this->loader->add_filter('determine_current_user', $plugin_public, 'determine_current_user', 10);
        //$this->loader->add_filter( 'rest_pre_dispatch', $plugin_public, 'rest_pre_dispatch', 10, 2 );
    }

```

It will only authenticate the user but will not validate the user on subsequent requests.

**Comment by marioshtika** [comment]
Maybe instead of changing the core plugin you could add a new filter.

For example:
```
add_filter('rest_pre_dispatch' , array( $this , 'rest_pre_dispatch_overwrite'), 11);
```

```
public function rest_pre_dispatch_overwrite($request) {
	if (is_wp_error($request)) {
		if($request->get_error_data('jwt_auth_bad_auth_header')) {
			return NULL;
		}
	}

        return $request;
}
```
