### ISSUE TITLE
How to implement user registration?

### ISSUE THREAD

**Issue by viankakrisna** [Tmeister/wp-api-jwt-auth#50]
Is there any examples regarding this?

**Comment by yurik94** [comment]
I have just done it today with insert wp_insert_user

**Comment by viankakrisna** [comment]
Also have done it. but it would be good if there's an example though. Right now I'm doing it like this:
```php
$role = $request->get_param( 'role' );

if ($role === 'admin' OR !in_array(['seller', 'buyer'], $role)){
	return new WP_Error('Cheating huh?');
}

$JWT = new Jwt_Auth_Public('jwt-auth', '1.1.0');

$id = wp_insert_user( array(
	'user_login'	=> $request->get_param('username'),
	'user_email'	=> $request->get_param('email'),
	'user_pass'		=> $request->get_param('password'),
	'nickname'		=> $request->get_param('nickname'),
	'first_name'	=> $request->get_param('name'),
	'user_url'		=> $request->get_param('web'),
	'role'			=> $role,
) );

if (is_wp_error($id)){
	return $id;
}

update_user_meta($id, 'name', $request->get_param('name'));
update_user_meta($id, 'phone', $request->get_param('phone'));
update_user_meta($id, 'phone', $request->get_param('phone'));
update_user_meta($id, 'address', $request->get_param('address'));
update_user_meta($id, 'facebook', $request->get_param('facebook'));
update_user_meta($id, 'twitter', $request->get_param('twitter'));
update_user_meta($id, 'linkedin', $request->get_param('linkedin'));
update_user_meta($id, 'google', $request->get_param('google'));

return $JWT->generate_token($request);
```

**Comment by sirdowan** [comment]
How did you get passed the /wp-json/wp/v2/users 401 (Unauthorized)?
My code is: 
`var settings = {
  "url": "http://mydomain/wp-json/wp/v2/users",
  "method": "POST",
  "headers": {
    "content-type": "application/x-www-form-urlencoded",
  },
  "data": {
    "username": "usr",
    "password": "user123",
    "email": "mymail@gmail.com"
  }
}`

Thanks!

**Comment by viankakrisna** [comment]
You need to register a custom rest route for registration.
here's the reference https://developer.wordpress.org/reference/functions/register_rest_route/

**Comment by sirdowan** [comment]
Thanks @viankakrisna 
And eh.. shall I create a new namespace? Or I'm allowed to rewrite the /users namespace? And I'm guessing would have to somehow call register_new_user as well?
If I'm not too bold, could I see how you've done it? :)
Thanks again!

**Comment by viankakrisna** [comment]
Just use a namespace to avoid confusion while reading it :)

Currently I'm abstracting the route registration with another function to avoid DRY. So i'm not sure it would help to copy paste the code here. In general, just follow the documentation of adding a new route and you'll be good to go. 👍

**Comment by ricardobrg** [comment]
Another way to achieve it is to call the endpoint through WP_REST_Request class like this

    $request = new WP_REST_Request( 'POST', '/wp-json/jwt-auth/v1/token' );
    $request->set_param( 'username', $username );
    $request->set_param( 'password', $password );
    $JWT = new Jwt_Auth_Public('jwt-auth', '1.1.0');
    $token = $JWT->generate_token( $request );

**Comment by suifengtec** [comment]
`php	/**
	 * [callback_signup description]
	 * @param  [type] $request [description]
	 * @return [type]          [description]
	 * @author suifengtec@qq.com
	 */
	public function callback_signup($request) {
		$secret_key = defined('JWT_AUTH_SECRET_KEY') ? JWT_AUTH_SECRET_KEY : false;

		if (!$secret_key) {
			return new WP_Error(
				'jwt_auth_bad_config',
				__('JWT is not configurated properly, please contact the admin', 'wp-api-jwt-auth'),
				array(
					'status' => 403,
				)
			);
		}
		$username = $request->get_param('username');
		if ($username != esc_sql($username)) {
			return new WP_Error(
				'jwt_auth_bad_username',
				__('User name is invalid.', 'jut'),
				array(
					'status' => 403,
				)
			);
		}

		if (username_exists($username)) {
			return new WP_Error(
				'jwt_auth_used_username',
				__('User name was used.', 'jut'),
				array(
					'status' => 403,
				)
			);
		}

		$useremail = $request->get_param('useremail');

		if (!is_email($useremail)) {
			return new WP_Error(
				'jwt_auth_invalid_email',
				__('Email is invalid.', 'jut'),
				array(
					'status' => 403,
				)
			);
		}
		if (email_exists($useremail)) {
			return new WP_Error(
				'jwt_auth_used_email',
				__('Email was used.', 'jut'),
				array(
					'status' => 403,
				)
			);
		}

		$password = $request->get_param('password');
		if (!$password && strlen($password) < 6) {
			return new WP_Error(
				'jwt_auth_invalid_password',
				__('User Password is invalid or too short.', 'jut'),
				array(
					'status' => 403,
				)
			);
		}

		$role = $request->get_param('role');
		if (in_array($role, JWT_User_Tweak_Module_Utils::get_specail_role_ids()) OR !in_array($role, JWT_User_Tweak_Module_Utils::get_role_ids())) {
			return new WP_Error('ERROR: user role error!');
		}

		$user_id = wp_insert_user(array(
			'user_login' => esc_sql($username),
			'user_email' => $useremail,
			'user_pass' => $request->get_param('password'),
			'nickname' => $username,
			'first_name' => $username,
			//'user_url' => $request->get_param('web'),
			'role' => $role,
		));
		if (is_wp_error($user_id)) {
			return $user_id;
		}

		$JWT = new Jwt_Auth_Public('jwt-auth', '1.1.0');

		return $JWT->generate_token($request);

	}`

**Comment by suifengtec** [comment]
```php
	/**
	 * [callback_signup description]
	 * @param  [type] $request [description]
	 * @return [type]          [description]
	 * @author suifengtec@qq.com
	 */
      public function callback_signup($request) {
		$secret_key = defined('JWT_AUTH_SECRET_KEY') ? JWT_AUTH_SECRET_KEY : false;

		if (!$secret_key) {
			return new WP_Error(
				'jwt_auth_bad_config',
				__('JWT is not configurated properly, please contact the admin', 'wp-api-jwt-auth'),
				array(
					'status' => 403,
				)
			);
		}
		$username = $request->get_param('username');
		if ($username != esc_sql($username)) {
			return new WP_Error(
				'jwt_auth_bad_username',
				__('User name is invalid.', 'jut'),
				array(
					'status' => 403,
				)
			);
		}

		if (username_exists($username)) {
			return new WP_Error(
				'jwt_auth_used_username',
				__('User name was used.', 'jut'),
				array(
					'status' => 403,
				)
			);
		}

		$useremail = $request->get_param('useremail');

		if (!is_email($useremail)) {
			return new WP_Error(
				'jwt_auth_invalid_email',
				__('Email is invalid.', 'jut'),
				array(
					'status' => 403,
				)
			);
		}
		if (email_exists($useremail)) {
			return new WP_Error(
				'jwt_auth_used_email',
				__('Email was used.', 'jut'),
				array(
					'status' => 403,
				)
			);
		}

		$password = $request->get_param('password');
		if (!$password || strlen($password) < 6) {
			return new WP_Error(
				'jwt_auth_invalid_password',
				__('User Password is invalid or too short.', 'jut'),
				array(
					'status' => 403,
				)
			);
		}

		$role = $request->get_param('role');
		if (in_array($role, JWT_User_Tweak_Module_Utils::get_specail_role_ids()) OR !in_array($role, JWT_User_Tweak_Module_Utils::get_role_ids())) {
			return new WP_Error('ERROR: user role error!');
		}

		$user_id = wp_insert_user(array(
			'user_login' => esc_sql($username),
			'user_email' => $useremail,
			'user_pass' => $request->get_param('password'),
			'nickname' => $username,
			'first_name' => $username,
			//'user_url' => $request->get_param('web'),
			'role' => $role,
		));
		if (is_wp_error($user_id)) {
			return $user_id;
		}

		$JWT = new Jwt_Auth_Public('jwt-auth', '1.1.0');

		return $JWT->generate_token($request);

	}
```

Utils methods:

```php	
public static function get_specail_role_ids() {

		$r = apply_filters('coolwp_jut_special_role_ids', [
			'administrator',
			'editor',
			'shop_manager',

		]);
		return $r;
	}

	public static function get_role_ids() {

		global $wp_roles;

		if (!isset($wp_roles)) {
			$wp_roles = new WP_Roles();
		}

		return array_keys($wp_roles->get_names());
	}
```

**Comment by suifengtec** [comment]
@viankakrisna  
```php
in_array(['seller', 'buyer'], $role)
```
the second param should be an array：
```php
in_array(  $role, ['seller', 'buyer'] )

```

**Comment by jacktator** [comment]
The following code should add User Registration via REST API to your WordPress Website. It supports Registration of 'subscriber' and 'customer'. Source code also available on [Github](https://github.com/SK8-PTY-LTD/wp-rest-user).

Add it to your function.php

    add_action('rest_api_init', 'wp_rest_user_endpoints');
    /**
     * Register a new user
     *
     * @param  WP_REST_Request $request Full details about the request.
     * @return array $args.
     **/
    function wp_rest_user_endpoints($request) {
      /**
       * Handle Register User request.
       */
      register_rest_route('wp/v2', 'users/register', array(
        'methods' => 'POST',
        'callback' => 'wc_rest_user_endpoint_handler',
      ));
    }
    function wc_rest_user_endpoint_handler($request = null) {
      $response = array();
      $parameters = $request->get_json_params();
      $username = sanitize_text_field($parameters['username']);
      $email = sanitize_text_field($parameters['email']);
      $password = sanitize_text_field($parameters['password']);
      // $role = sanitize_text_field($parameters['role']);
      $error = new WP_Error();
      if (empty($username)) {
        $error->add(400, __("Username field 'username' is required.", 'wp-rest-user'), array('status' => 400));
        return $error;
      }
      if (empty($email)) {
        $error->add(401, __("Email field 'email' is required.", 'wp-rest-user'), array('status' => 400));
        return $error;
      }
      if (empty($password)) {
        $error->add(404, __("Password field 'password' is required.", 'wp-rest-user'), array('status' => 400));
        return $error;
      }
      // if (empty($role)) {
      //  $role = 'subscriber';
      // } else {
      //     if ($GLOBALS['wp_roles']->is_role($role)) {
      //      // Silence is gold
      //     } else {
      //    $error->add(405, __("Role field 'role' is not a valid. Check your User Roles from Dashboard.", 'wp_rest_user'), array('status' => 400));
      //    return $error;
      //     }
      // }
      $user_id = username_exists($username);
      if (!$user_id && email_exists($email) == false) {
        $user_id = wp_create_user($username, $password, $email);
        if (!is_wp_error($user_id)) {
          // Ger User Meta Data (Sensitive, Password included. DO NOT pass to front end.)
          $user = get_user_by('id', $user_id);
          // $user->set_role($role);
          $user->set_role('subscriber');
          // WooCommerce specific code
          if (class_exists('WooCommerce')) {
            $user->set_role('customer');
          }
          // Ger User Data (Non-Sensitive, Pass to front end.)
          $response['code'] = 200;
          $response['message'] = __("User '" . $username . "' Registration was Successful", "wp-rest-user");
        } else {
          return $user_id;
        }
      } else {
        $error->add(406, __("Email already exists, please try 'Reset Password'", 'wp-rest-user'), array('status' => 400));
        return $error;
      }
      return new WP_REST_Response($response, 123);
    }

IMHO, a more better way would to include the additional function as a seperate plugin. So even when your user changed theme, your api calls won't be affected.

Therefore I've developed a **plugin** for User Registration via REST API in WordPress. Better yet, it supports creating 'customer' for WooCommerce too!

[WP REST User](https://wordpress.org/plugins/wp-rest-user/), check it out if you want.

**Comment by suifengtec** [comment]
@jacktator 

Thinks for your plugin [WP REST User](https://wordpress.org/plugins/wp-rest-user/)

I found 2 bugs as following.

/public/class-wp-user-public.php

```php

		// run the action
		do_action('retrieve_password', $user_user_login);

```
should be:


```php
	// run the action
       do_action('retrieve_password', $user_login);

```

and the following user role keys should be all in lowercase:

```
				if ($role == 'administrator' || $role == 'Editor' || $role == 'Author') {
					$error->add(406, __("Role field 'role' is not a permitted. Only 'contributor', 'subscriber' and your custom roles are allowed.", 'wp_rest_user'), array('status' => 400));
					return $error;
				} else {
					// Silence is gold
				}


```

**Comment by virtualLast** [comment]
If creating a custom plugin and also wanting to introduce user registration this is roughly how I managed it.
```
register_rest_route($this->namespace, '/' . $this->restBase . '/register', [
                'methods' => 'POST',
                'callback' => [$this, 'registerUser'],
                'permission_callback' => [$this, 'registerUserPermissionsCheck'],
                'args' => $this->registerUserSchema()
            ]
        );
```
We will ignore the schema here for brevity as well as the permissions check.

```
public function registerUser(\WP_REST_Request $request)
    {
        $error = new \WP_Error();
        $secretKey = defined('JWT_AUTH_SECRET_KEY') ? JWT_AUTH_SECRET_KEY : false;
        if (!$secretKey) {
            $error->add('jwt_auth_bad_config',
                __('JWT is not configured properly, please contact the admin', $this->pluginName),
                [
                    'status' => 403,
                ]);
            return $error;
        }

        // empty values check
        if (empty($request['username'])) {
            $error->add('rest_user_invalid_username', __('A username is required.', $this->pluginName),
                ['status' => 400]);
            return $error;
        }
        if (empty($request['email']) || !is_email($request['email'])) {
            $error->add('rest_user_invalid_email', __('An email is required.', $this->pluginName), ['status' => 400]);
            return $error;
        }
        if (empty($request['password'])) {
            $error->add('rest_user_invalid_password', __('A password is required.', $this->pluginName),
                ['status' => 400]);
            return $error;
        }
        if (empty($request['date_of_birth'])) {
            $error->add('rest_user_invalid_date_of_birth', __('A date of birth is required.', $this->pluginName),
                ['status' => 400]);
            return $error;
        }

        // sanitize username, validate username
        if (username_exists($request['username'])) {
            $error->add('rest_user_invalid_username', __('Username already exists. Reset password?', $this->pluginName),
                ['status' => 400]);
            return $error;
        }
        $username = sanitize_user($request['username'], true);

        // sanitize email, validate email
        if (email_exists($request['email'])) {
            $error->add('rest_user_invalid_email', __('Email already exists. Reset password?', $this->pluginName),
                ['status' => 400]);
            return $error;
        }
        $email = sanitize_email($request['email']);

        // sanitize password, validate password -- the password is hashed during wp_insert_user,
        // so we are just checking string length
        if (strlen($request['password']) < 8) {
            $error->add('rest_user_invalid_password',
                __('A minimum of 8 characters is required for the password.', $this->pluginName), ['status' => 400]);
            return $error;
        }

        // sanitize, validate date_of_birth is user over 13 years of age.
        // 13 years === 410248800 seconds
        $now = Carbon::now();
        $yearsAgo = $now->subYears(13);
        try {
            $dateOfBirth = Carbon::createFromFormat('Y-m-d H:i:s', $request['date_of_birth']);
        } catch (\Carbon\Exceptions\InvalidDateException $e) {
            $error->add('rest_user_invalid_date_of_birth', $e->getMessage(), ['status' => 400]);
            return $error;
        }

        if ($dateOfBirth->greaterThanOrEqualTo($yearsAgo)) {
            $error->add('rest_user_invalid_date_of_birth',
                __('A user must be at least 13 years of age.', $this->pluginName), ['status' => 400]);
            return $error;
        }

        $userID = wp_create_user($username, $request['password'], $email);
        if (is_wp_error($userID)) {
            return $userID;
        }
        $user = get_user_by('id', $userID);
        $user->set_role('subscriber');
        add_user_meta($userID, 'date_of_birth', $request['date_of_birth'], true);
        $url = rest_url('jwt-auth/v1/token');
        $token = wp_remote_post($url, [
            'sslverify' => false, // change to true once in prod
            'body' => [
                'username' => $username, // request username
                'password' => $request['password'] // request password
            ]
        ]);

        if (is_wp_error($token)) {
            return $token;
        } else {
            $headers = wp_remote_retrieve_headers($token);
            $body = wp_remote_retrieve_body($token);
            $code = wp_remote_retrieve_response_code($token);
            $message = wp_remote_retrieve_response_message($token);
            switch ($code) {
                case 200:
                    $jsonUser = json_decode($body);
                    $response = new \WP_REST_Response();
                    $response->set_status(201);
                    $response->set_data((array) $jsonUser);
                    return $response;
                    break;
                case 403:
                    $jsonError = json_decode($body);
                    $error->add($jsonError->code, $jsonError->message, (array)$jsonError->data);
                    return $error;
                    break;
                default:
                    $error->add('rest_user_login_failed', __('Unable to log you in.', $this->pluginName),
                        ['status' => 500]);
                    return $error;
                    break;
            }
        }
    }
```

**Comment by Steffi3rd** [comment]
@jacktator Why do you suggest to use WP Rest User? 

I just installed it and add your code below in my `functions.php`. It works indeed.
But I just uninstalled and it works exactly the same way...

What's more?

But thanks for the code!


> add_action('rest_api_init', 'wp_rest_user_endpoints');
> /**
>  * Register a new user
>  *
>  * @param  WP_REST_Request $request Full details about the request.
>  * @return array $args.
>  **/
> function wp_rest_user_endpoints($request) {
>   /**
>    * Handle Register User request.
>    */
>   register_rest_route('wp/v2', 'users/register', array(
>     'methods' => 'POST',
>     'callback' => 'wc_rest_user_endpoint_handler',
>   ));
> }
> function wc_rest_user_endpoint_handler($request = null) {
>   $response = array();
>   $parameters = $request->get_json_params();
>   $username = sanitize_text_field($parameters['username']);
>   $email = sanitize_text_field($parameters['email']);
>   $password = sanitize_text_field($parameters['password']);
>   // $role = sanitize_text_field($parameters['role']);
>   $error = new WP_Error();
>   if (empty($username)) {
>     $error->add(400, __("Username field 'username' is required.", 'wp-rest-user'), array('status' => 400));
>     return $error;
>   }
>   if (empty($email)) {
>     $error->add(401, __("Email field 'email' is required.", 'wp-rest-user'), array('status' => 400));
>     return $error;
>   }
>   if (empty($password)) {
>     $error->add(404, __("Password field 'password' is required.", 'wp-rest-user'), array('status' => 400));
>     return $error;
>   }
>   // if (empty($role)) {
>   //  $role = 'subscriber';
>   // } else {
>   //     if ($GLOBALS['wp_roles']->is_role($role)) {
>   //      // Silence is gold
>   //     } else {
>   //    $error->add(405, __("Role field 'role' is not a valid. Check your User Roles from Dashboard.", 'wp_rest_user'), array('status' => 400));
>   //    return $error;
>   //     }
>   // }
>   $user_id = username_exists($username);
>   if (!$user_id && email_exists($email) == false) {
>     $user_id = wp_create_user($username, $password, $email);
>     if (!is_wp_error($user_id)) {
>       // Ger User Meta Data (Sensitive, Password included. DO NOT pass to front end.)
>       $user = get_user_by('id', $user_id);
>       // $user->set_role($role);
>       $user->set_role('subscriber');
>       // WooCommerce specific code
>       if (class_exists('WooCommerce')) {
>         $user->set_role('customer');
>       }
>       // Ger User Data (Non-Sensitive, Pass to front end.)
>       $response['code'] = 200;
>       $response['message'] = __("User '" . $username . "' Registration was Successful", "wp-rest-user");
>     } else {
>       return $user_id;
>     }
>   } else {
>     $error->add(406, __("Email already exists, please try 'Reset Password'", 'wp-rest-user'), array('status' => 400));
>     return $error;
>   }
>   return new WP_REST_Response($response, 123);
> }

**Comment by biasijunior** [comment]
> https://developer.wordpress.org/reference/functions/register_rest_route/

This must be labeled as the easiest answer I have seen so far

**Comment by Dynkin** [comment]
@jacktator and @virtualLast made great code snippets! Works like a charm!
