### ISSUE TITLE
Malformed authorization header when wp-login.php is password protected

### ISSUE THREAD

**Issue by brunoguimaraes** [Tmeister/wp-api-jwt-auth#51]
Any rest api endpoint returns "malformed authorization header" when wp-login.php is password protected.

Steps to reproduce this issue: 
https://codex.wordpress.org/Brute_Force_Attacks#Password_Protect_wp-login.php

**Comment by jenilk** [comment]
Hi @brunoguimaraes 

We are facing the same issue. We restricted only the wp-admin and wp-login.php but sometime this error get occurred to rest api end points.  Something unusual behavior but I am sure something is related to Basic Auth.

Can you please share your findings to resolve the issue?

Thanks
Jenil
