### ISSUE TITLE
Always  jwt_auth_bad_auth_header with  status 403

### ISSUE THREAD

**Issue by appsgit1** [Tmeister/wp-api-jwt-auth#62]
I am trying to authenticate my credentials with this and always getting this response. 
{
  "code": "jwt_auth_bad_auth_header",
  "message": "Authorization header malformed.",
  "data": {
    "status": 403
  }
}

My .htaccess file is like below

```
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress
```

My url is : http://domain.com/wp-json/jwt-auth/v1/token (post)

i have setup my token in the config file as well

define('JWT_AUTH_SECRET_KEY', 'dfdfgdfgdfreerertesting');

Hope someone will help me

**Comment by gravyplaya** [comment]
I am having the same exact issue.. 
I added the lines to my htaccess. I an getting the following error.
{"code":"jwt_auth_bad_auth_header","message":"Authorization header malformed.","data":{"status":403}}
I am on wpengine and php7.

---- htaccess begin ------
```
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
```
-----htaccess end-----

I can see the header in the request:
authorization:Basic Y2tfZGNmMzkyZTI1......

**Comment by Orabig** [comment]
TL;DR;
Move the definition of JWT_AUTH_SECRET_KEY to the top of your wp-config.php file

Detailed solution :

As stated in the installation doc of the plugin,
the JWT needs a secret key to sign the token this secret key must be unique and never revealed.

Thus, you must add this line into your wp-config.php file

define('JWT_AUTH_SECRET_KEY', 'your-top-secrect-key');
However, what the doc does not say, is that you should not put this at the end of the file.
Insert this line just after the other definitions (AUTH_KEY, SECURE_AUTH_KEY, ... NONCE_SALT), and the 403 error should be gone.

I guess that's because the definition of JWT_AUTH_SECRET_KEY must be done before require_once(ABSPATH . 'wp-settings.php');

**Comment by hafizc007** [comment]
@Orabig  I have tried your method and still getting the same error message. can anybody help?

**Comment by kwfricke** [comment]
This was a bit confusing...you do NOT use Basic Authentication. You simply pass the username and password as form field parameters in the request to get the token back. I hope this saves someone an hour...

**Comment by saft1g** [comment]
run it in postman:
Method: POST
Authorization:  No Auth
Body: form-data with keys username and password (and their values)

results in:
`{
    "token": "eyJ0eXAiOiJKV1QiLCJhbXXXXXXXXXXXXXXXmQXXXXXf4zeXXXXZhMo",
    "user_email": "xxxx@xxx.com",
    "user_nicename": "xxxxx",
    "user_display_name": "xxxx xxxxx"
}`

**Comment by devasia2112** [comment]
I want to provide login using another application, I'm able to get this token, user_email, user_nicename and user_display_name. 
Now what should I do with the token in order to enable users log in with WP?
I have my own login page and it's not part of wordpress installation, I just want to create a session, then user can purchase items with the woocommerce.
thanks.

**Comment by devasia2112** [comment]
> run it in postman:
> Method: POST
> Authorization: No Auth
> Body: form-data with keys username and password (and their values)
> 
> results in:
> `{ "token": "eyJ0eXAiOiJKV1QiLCJhbXXXXXXXXXXXXXXXmQXXXXXf4zeXXXXZhMo", "user_email": "xxxx@xxx.com", "user_nicename": "xxxxx", "user_display_name": "xxxx xxxxx" }`

Whatever No-Auth or Basic Auth it return the same message: `Fatal error: Uncaught exception 'Automattic\WooCommerce\HttpClient\HttpClientException' with message 'Error: Authorization header malformed. [jwt_auth_bad_auth_header]' in`

It was working, but after upgrading the plugin, it just stop working.

**Comment by avks** [comment]
I had the same issue. Moving these two lines:
```
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
```
Before `</IfModule>` solved my issue.

**Comment by devasia2112** [comment]
I was running on nginx. Anyway I decided not use this plugin anymore. I can't have interruptions in my system due to plugins update.

**Comment by avks** [comment]
So what are you using instead?

**Comment by marioshtika** [comment]
Maybe something like this could help https://github.com/Tmeister/wp-api-jwt-auth/issues/48#issuecomment-503291246

**Comment by pacerdev** [comment]
Somebody will read this from a Google search. I found this from doing some googling.

Here's the way you get this going:

PREP: Enterthese lines in .htaccess (must be the first three lines):
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]

PREP 2: 
Generate a secret key here: https://api.wordpress.org/secret-key/1.1/salt/ (I copied out SECURE_AUTH_KEY)
Add this line in wp-config.php after define('NONCE_SALT'...
define('JWT_AUTH_SECRET_KEY', 'pasteyoursecretkey');

1. POST method in Postman. 
2. Enter your URL (i.e. http://whatever.xxx/wp-json/jwt-auth/v1/token)
3. No Auth
4. Body - select form data. 
5. Enter two keys: KEY username VALUE youruser, KEY password VALUE yourpassword
6. Send. You'll get your token.

**Comment by Bolas** [comment]
I got it working by adding this
`RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]`

instead of this
`RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]`

in my .htaccess file.

and I also added Bearer before my authorization token, like this
`Bearer XXXXXXXX.YYYYYYYYY.ZZZZZZZZ`

**Comment by izhan1972** [comment]
> run it in postman:
> Method: POST
> Authorization: No Auth
> Body: form-data with keys username and password (and their values)
> 
> results in:
> `{ "token": "eyJ0eXAiOiJKV1QiLCJhbXXXXXXXXXXXXXXXmQXXXXXf4zeXXXXZhMo", "user_email": "xxxx@xxx.com", "user_nicename": "xxxxx", "user_display_name": "xxxx xxxxx" }`

POST http://localhost/latih-prd/wp-json/jwt-auth/v1/token

**Comment by iiKulakov** [comment]
> I got it working by adding this
> `RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]`
> 
> instead of this
> `RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]`
> 
> in my .htaccess file.
> 
> and I also added Bearer before my authorization token, like this
> `Bearer XXXXXXXX.YYYYYYYYY.ZZZZZZZZ`

Worked for me too. 
Thanks!

**Comment by ahmedelatab** [comment]
@pacerdev 

That's what I want.
Working like charm!

**Comment by ghost** [comment]
> 
> 
> I got it working by adding this
> `RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]`
> 
> instead of this
> `RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]`
> 
> in my .htaccess file.
> 
> and I also added Bearer before my authorization token, like this
> `Bearer XXXXXXXX.YYYYYYYYY.ZZZZZZZZ`

Many thanks. This worked perfectly for me.

**Comment by dasbuilder** [comment]
What would be an appropriate header for JWT auth if someone isn't using htaccess? I'm on WPE and PHP 7.4 doesn't have htaccess - is there an appropriate header? 
I added this Nginx rule, but this hasn't worked. Any tips? 

```
#JWT auth
if ($http_JWT_AUTHORIZATION ~ "^(.*)"){
	set $rule_0 1;
}
if ($rule_0 = "1"){
	set $http_JWT_AUTHORIZATION %1;
}
```

**Comment by pacerdev** [comment]
You can find info on forming the Ngnix version of this here:

https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-jwt-authentication/

**Comment by yeahsky** [comment]
https://www.redren.net/8101.html this page has some pictures in detail, but it is  in  Chinese, you can use google to translate it. It  will help.

**Comment by wongkevinmanuel** [comment]
Install the JWT Authentication for WP-API plugin, activate and as the official page says configure the .htaccess files, wp-config.php. But I get error, when I make a post request, in postman:
`{
    "code": "jwt_auth_bad_auth_header",
    "message": "Authorization header malformed.",
    "data": {
        "status": 403
    }
}`

Archive .htaccess:

`<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /wordpress/
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /wordpress/index.php [L]

SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
</IfModule>`

Archive wp-config.php:

`define( 'AUTH_KEY',         'QyGu$K8z1tt*X8S1}kA;*lRr-rmY4l&)H36`aS6=k1:7_`sM0?ZEfM8ro@lsu-H<' );
define( 'SECURE_AUTH_KEY',  'F30ADghK*dA3i~{;0`BNE!6pOV|Wdo:9C5VjDQr]50`{,lE0.dZY)/V,jxI)k#!?' );
define( 'LOGGED_IN_KEY',    'G x`)3XecQ8L.+hVMXHbzl|,wIxW|D`5nBo:&h=NY.E{G52kxcY&qg4HY(>X> E5' );
define( 'NONCE_KEY',        '%ALdMo=~lS9HYZG4*[;~[v+p_8Jm{D$;,f2A2.]t?Rp)0MR2Ev-Tr/#rP8#VEB|G' );
define( 'AUTH_SALT',        '=9P1`nvGzj~>jKRSFmFffn%N#.&$V, H!Oj)L29vpGshDh8 jB|Z>y@7/s>0|.>L' );
define( 'SECURE_AUTH_SALT', '@9pXtG!-?T.^x~P//P^2fFzX1RzWk%gy-v=ctqWh_Q*653;LfO%27& s_aRfEq/I' );
define( 'LOGGED_IN_SALT',   'TCB#O@L8f|!FG_1N7Uvilk:0v=CC}FQ1iG#~2Uo#tfuRST2F7F(8Yd 1eD8|OBYw' );
define( 'NONCE_SALT',       'L@&ddudAH6_Omj?si%mh1{Z3RuqA:CG3UtYujaci@84n+?%~`[d(IV;d:kP]ApSt' );
define('JWT_AUTH_SECRET_KEY', '123456');
define('JWT_AUTH_CORS_ENABLE', true);`

**Comment by wongkevinmanuel** [comment]
This solution, edit the /jwt-authentication-for-wp-rest-api/public/class-jwt-auth-public.php file to automatically set the Bearer token if Basic Authentication was being performed and the token was missing. Look at this link, find the details.
https://wordpress.org/support/topic/fix-basic-authentication-jwt_auth_bad_auth_header-error/

**Comment by DrLightman** [comment]
> I got it working by adding this `RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]`
> 
> instead of this `RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]`
> 
> in my .htaccess file.
> 
> and I also added Bearer before my authorization token, like this `Bearer XXXXXXXX.YYYYYYYYY.ZZZZZZZZ`

Well, thank you!

I don't know how and why but this worked.
In my case the line was:

`RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]`

And it didn't work.
