### ISSUE TITLE
Forgot Password Feature

### ISSUE THREAD

**Issue by nickrobinson352** [Tmeister/wp-api-jwt-auth#63]
I am trying to incorporate a forgot password feature in my application and am trying to figure out how to make this work. I have created a custom endpoint that will receive the user's email whose password needs to be reset, but when I call it, the JWT authentication error checks kicks in rejecting my request. How do I bypass the authentication check for just this REST Endpoint as the user wont be able to authenticate till the password is reset.

Is the solution simply to disable the 'permission_callback' in my custom endpoint ? If I do this, I cannot access any Wordpress API functions since I am not logged in.

**Comment by virtualLast** [comment]
Bump*
