### ISSUE TITLE
error when uploading  jwt-authentication-for-wp-rest-api.1.2.0 Plugine

### ISSUE THREAD

**Issue by Sajibekanti** [Tmeister/wp-api-jwt-auth#66]
Hi 
I have Facing Problem When uploading error when uploading  jwt-authentication-for-wp-rest-api.1.2.0 Plugins In Wordpress Admin Panel 

I can't Access wp-admin/ 
When Upload and Install  jwt-authentication-for-wp-rest-api 

Where is mistake ?

**Comment by jrsarath** [comment]
Install the plugin directly from wordpress Plugin Directory..
go to https://yourdomain/wp-admin -> Plugins ->  add new -> search for JWT-authentication 
you will be able to install the jwt authentication plugin directly from wordpress repo..
