### ISSUE TITLE
Hints for NGINX

### ISSUE THREAD

**Issue by mrbm** [Tmeister/wp-api-jwt-auth#67]
Love the hints you have for Apache and WP Engine, wondering if you could provide some suggestions for needed additions to the NGINX files

Thanks!

**Comment by larssn** [comment]
Have you tried without any rules?

AFAIK, the authorization header is not disabled in nginx.

**Comment by tzkmx** [comment]
I'm using in my only NginX installation (no Apache middleman necessary), and works without issues.
