### ISSUE TITLE
Wrong password returning html

### ISSUE THREAD

**Issue by raphaelnikson** [Tmeister/wp-api-jwt-auth#71]
When I enter a wrong password, the html of the current page route is returned.

**Comment by mygeweb** [comment]
I think it is because you may use `wp_login_failed` action

**Comment by raphaelnikson** [comment]
Yes man.. 
I already solve

**Comment by Botsy** [comment]
Hi, can you please share if you have found what causes the issue? It still persists.

**Comment by mygeweb** [comment]
I've done like this:
```
add_filter( 'authenticate', '_wp_authenticate', 10, 3 ); // API authenticate filter
function _wp_authenticate( $ret, $username, $password ) {
	if(defined('REST_REQUEST') and REST_REQUEST){	// Apply for API request only
		remove_action( 'wp_login_failed', '_wp_login_failed' );
		$possible_user = get_user_by( 'email', $username );
	    if( $possible_user and wp_check_password( $password, $possible_user->data->user_pass, $possible_user->ID) ) {
			return $possible_user;
		}
		return null;
	}
}
```
there is `wp_login_failed` action in your theme some where and you have to remove it here.

**Comment by Botsy** [comment]
Thank you very much! I already have found out that wp_login_failed action was causing the issue by the time you responded, but wasn't sure how to remove the action for API calls only, so again, Thank you! Much appreciated! :)
