### ISSUE TITLE
Its not validating header while using rest_url_prefix in WP REST API

### ISSUE THREAD

**Issue by kalpitpandit** [Tmeister/wp-api-jwt-auth#75]
When I change namespace from wp-json to /api, Its not validating header and giving 401 error. Is there any workaround? 

Is there any way to refresh token by giving current jwt or refresh token?

**Comment by kbauman** [comment]
I had the same issue. It finally occurred to me that a filter to change the rest url prefix, added in the functions.php, runs too late. The JWT plugin is looking for the rest url prefix, before the functions.php filter runs. So, when the plugin checks for the rest url prefix it still gets 'wp-json'. 

I fixed it by creating a plugin that changed the rest url prefix.
