### ISSUE TITLE
Is further development abandoned?

### ISSUE THREAD

**Issue by jonathan-dejong** [Tmeister/wp-api-jwt-auth#77]
Hi! 

Have you abandoned this plugin? There's unadressed PRs from December and forward.
We are working on a project now which requires this + more like revoke abilities in wp admin etc. 

I've already forked the project in github and started making the necessary changes and updates. If you no longer intend to continue working on this would it be okay if we publish a new plugin based on this? (Will refactor a lot of the code too).

Best 
/ Jonathan

**Comment by tribalboy3000** [comment]
Any response on this? If it's not supported I need to find another solution.

**Comment by jonathan-dejong** [comment]
Hi @tribalboy3000 

If you like you can download the develop branch from my fork here:
https://github.com/jonathan-dejong/wp-api-jwt-auth/tree/develop

It contains the first version of UUID token session and the ability to revoke these in the user profile (along with some useful information listed).

**Comment by tkserver** [comment]
I'm working on an app which will require authentication and wondering about this myself.  I will look at your branch @jonathan-dejong

**Comment by jonathan-dejong** [comment]
I'll be pushing up some more changes today. I've added two new endpoints. One for logging out (and removing the session key) and one for requesting a new password.

**Comment by tribalboy3000** [comment]
Hi @jonathan-dejong, I just checked it out but didn't see any reference to logging out or new password. Did I miss it?

**Comment by jonathan-dejong** [comment]
Hi @tribalboy3000 

Sorry it's up now :) 
There's an endpoint `token/resetpassword` that takes a POST with a body of username/email. 
And there's a `token/revoke` that takes a POST without any body content. It'll check current user and revoke their token (essentially logging them out).

**Comment by jdozierezell** [comment]
Hi @jonathan-dejong,

Does this plugin also block unauthorized calls to the API? The readme makes it sound like it does, and I've followed all the configuration steps, but I'm still able to fully access the REST API without authentication. I can keep troubleshooting, but right now I'm just trying to make sure I'm not barking up the wrong tree. Thanks!

**Comment by tkserver** [comment]
Hey @jonathan-dejong is there a place to post issues in your repo?  Will your version work on localhost?  Your dev version 500'd me, but your version 1.2.3 does not.

**Comment by jonathan-dejong** [comment]
Hi @tkserver 

Can you please activate WP_DEBUG and check your debug log for potential errors causing the 500 error. I'm using it myself on a local dev site with no issues so I need your help to locate the error :) 

I've also turned on issues on my repo.

**Comment by jonathan-dejong** [comment]
Hi @jdozierezell 

It does block unauthorized calls that would require you to be logged in normally. So you could not update or create content but per default in WordPress most "Read" API endpoints are open to the public. You could very easily block all of these and require authorization with a little snippet in a custom plugin or your themes functions.php. 

Something like this should work:

```
function require_login_wp_rest_api( $result ) {		
    if( ! is_user_logged_in() ) {
        return false;
    }
    return $result;
	     
}
add_filter( 'json_authentication_errors', 'require_login_wp_rest_api' );
```

**Comment by jonathan-dejong** [comment]
Heyo!

It's been a month and the author has not responded.
So I've rewritten the plugin almost from ground up and added features such as an interface to revoke and view tokens on a profile and a settings page which can be used instead of wp-config values.

https://github.com/jonathan-dejong/simple-jwt-authentication

**Comment by gordielachance** [comment]
Would be nice if the plugin author would tell anything about this.
I'm currently migrating to your plugin.
