### ISSUE TITLE
Error 401 with WordPress 4.8

### ISSUE THREAD

**Issue by leonardlin** [Tmeister/wp-api-jwt-auth#79]
I updated to WP 4.8 and the plugin has stopped working.

I can get a token but when I try to create or update a blog post it says:
"401 Does not have correct role".

It looks like to me it ignores the token passed in the header when posting to the API.
Can someone confirm this?

**Comment by noureddine-latreche** [comment]
Me too
"Sorry, you are not allowed to create posts as this user"

**Comment by Cyanbird** [comment]
Me too , it makes me confused.

**Comment by chrisgate** [comment]
this error is in WP 4.9 too any solutions @Tmeister .

Thanks in anticipations.
