### ISSUE TITLE
How to get $token in Hooks?

### ISSUE THREAD

**Issue by bobsilon** [Tmeister/wp-api-jwt-auth#8]
Hi there, in documentation described how to modify all the response array before to dispatch it to the client by using [jwt_auth_token_before_dispatch](https://github.com/Tmeister/wp-api-jwt-auth#jwt_auth_token_before_dispatch) filter.
But how to get **token**?

``` php
$data = array(
    'token' => $token,
    'user_email' => $user->data->user_email,
    'user_nicename' => $user->data->user_nicename,
    'user_display_name' => $user->data->display_name,
);
```

**Comment by bobsilon** [comment]
Oh I find it in [source](https://github.com/Tmeister/wp-api-jwt-auth/blob/develop/public/class-jwt-auth-public.php#L105).
But I think it's a good idea if we have an api in `Jwt_Auth_Public` class to get the **token** itself.

**Comment by Tmeister** [comment]
What you want to accomplish?

**Comment by bobsilon** [comment]
@Tmeister Thanks for getting back to me. I just wanted to change the response, remove some existing and add some new. And I was confused how to generate token inside my `functions.php` file of theme.
Few days ago I did recheck the source of plugin [and I saw](https://github.com/Tmeister/wp-api-jwt-auth/blob/develop/public/class-jwt-auth-public.php#L164) you attached two variables `$data` and `$user` to the hook. So I did what I want as below:

``` php
add_filter('jwt_auth_token_before_dispatch', 'do_something', 10, 2);
function do_something($data, $user)
{
    $roles = getRoles();
    return $data = array(
      'token'    => $data['token'],
      'username' => $user->data->user_nicename,
      'role'     => $roles['userRoles'][$user->roles[0]],
    );
}
```

I think the documentation, lacks on how to use these hooks. Or I am too rookie. :smile:

**Comment by frank-liu** [comment]
save my time. thanks

**Comment by egystr** [comment]
@bobsilon that was very useful, cheers

**Comment by bilalCatic** [comment]
Using this filter, I get null response, what could be reason ? Even when I change function to just return $data, still same result 
EDIT : Solution
Changed add_filter line to this and now it works as expected :

> add_filter('jwt_auth_token_before_dispatch', array(\_\_CLASS\_\_, 'do_something'), 10, 2);
