### ISSUE TITLE
[query] Can I allow WooCommerce consumer key access at the same time?

### ISSUE THREAD

**Issue by lofidevops** [Tmeister/wp-api-jwt-auth#87]
**Steps to reproduce:**

* Perform a WooCommerce REST API query against Wordpress site
  * Authenticate using the WooCommerce consumer key (as normal)
* Activate JWT plugin
* Repeat the query (with consumer key authentication)

**What should happen:**

* First query is successful
* Second query is successful

**What happens instead:**

* First query is successful (correct)
* Second query fails with

````
{'code': 'jwt_auth_bad_auth_header',
 'data': {'status': 403},
 'message': 'Authorization header malformed.'}
````

How can I continue to perform queries with WooCommerce consumer key authentication (these are for system queries, logging, etc) but still activate JWT for user-orientated authentication?

**Comment by lofidevops** [comment]
This is similar to the following issues/queries but none of these has a recorded solution:
* https://github.com/Tmeister/wp-api-jwt-auth/issues/48
* https://github.com/Tmeister/wp-api-jwt-auth/issues/62
* https://github.com/Tmeister/wp-api-jwt-auth/issues/3

Also posted as a Q&A to https://wordpress.stackexchange.com/q/283874/31388

**Comment by lofidevops** [comment]
I get the same error when I try `https://DOMAIN/wp-json/jwt-auth/v1/token?username=test&password=test` (presumably this should instead result in an authentication failure)

**Comment by lofidevops** [comment]
Ok, fixed the token request issue by paying closer attention to the example. In Postman I did this:

````
POST https://DOMAIN/wp-json/jwt-auth/v1/token
* Authorization: `No Auth`
* Headers: blank
* Body: `form-data`
  * key: username, value: test
  * key: password, value: test
````

...and replicated that successfully as a Python request:

    import woocommerce.api

    wcapi = woocommerce.api(
        url="https://DOMAIN",
        consumer_key=WOO_CONSUMER_KEY,
        consumer_secret=WOO_CONSUMER_SECRET,
        wp_api=True,
        version="jwt-auth/v1",
    )

    wcapi.post("token", {"username": "test", "password": "test"})
    # this adds consumer details as oauth 1.0 credentials to URL, but they don't seem to interfere
    # tested oauth-in-url method with postman and same result there

So this now comes back to the original issue. My previously working WP API requests with OAuth 1.0 (consumer key) authentication are no longer working because Wordpress is looking for JWT headers.

Can I configure WP/JWT to allow OAuth 1.0 style queries *in addition to* JWT queries?

**Comment by lofidevops** [comment]
Confirmed with Postman that OAuth 1.0 style queries with consumer key in the URL work:

````
GET https://DOMAIN/wp-json/wc/v1/subscriptions
* Authorization: `OAuth 1.0`
  * Consumer key: FILLED IN
  * Consumer secret: FILLED IN
  * Other fields: blank
* Headers: blank
* Body: blank
````

Returns expected results. Python equivalent fails with:

````
<Response [401]>
{'code': 'woocommerce_rest_authentication_error',
 'data': {'status': 401},
 'message': 'Invalid signature - provided signature does not match.'}
````

...but this does not appear to be caused by the JWT plugin (works in Postman, fails in Python).

It seems the solution for non-JWT queries was to force OAuth 1.0 authentication in the URL, not the headers.

**Comment by lofidevops** [comment]
The prototype code above actually only worked for HTTP domains. For HTTPS domains you would still receive {'code': 'jwt_auth_bad_auth_header', 'data': {'status': 403}, 'message': 'Authorization header malformed.'}

For an HTTPS query you need `query_string_auth=True` as follows:

```
import woocommerce.api

wcapi = woocommerce.api(
    url="https://DOMAIN",
    consumer_key=WOO_CONSUMER_KEY,
    consumer_secret=WOO_CONSUMER_SECRET,
    wp_api=True,
    version="jwt-auth/v1",
    query_string_auth=True,
)

wcapi.post("token", {"username": "test", "password": "test"})
```

**Comment by ferromariano** [comment]
Is there any solution?

**Comment by ferromariano** [comment]
yeaaaah

@kwill 
modifying the request header of the woocommerce api, and adding
`'Authorization' => 'Bearer'. $token;`
it works :)

**Comment by zaklampert** [comment]
using [queryStringAuth](http://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-https)

e.g.
```
var WooCommerceAPI = require('woocommerce-api');

var WooCommerce = new WooCommerceAPI({
  url: 'https://example.com',
  consumerKey: 'consumer_key',
  consumerSecret: 'consumer_secret',
  wpAPI: true,
  version: 'wc/v2',
  queryStringAuth: true // Force Basic Authentication as query string true and using under HTTPS
});
```

Allowed me to use Basic Auth for woocommerce and Bearer Tokens where necessary.

**Comment by DibranMulder** [comment]
![image](https://user-images.githubusercontent.com/5592416/50728467-7625d400-112a-11e9-8b6a-1334d0a3354b.png)
Its important to notice that the Woocommerce implementation doesn't expect empty parameters. A lot of libraries do include empty parameters into the signature.

**Comment by marioshtika** [comment]
Maybe something like this could help https://github.com/Tmeister/wp-api-jwt-auth/issues/48#issuecomment-503291246
