### ISSUE TITLE
.htaccess help

### ISSUE THREAD

**Issue by jwight1234** [Tmeister/wp-api-jwt-auth#9]
I can't get .htaccess to work on godaddy server

This is what I have in the .htaccess file.

```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

<IfModule mod_rewrite.c>
RewriteEngine on
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
</IfModule>
```

This is the error I get when i attempt to login

XMLHttpRequest cannot load http://site.www/wp-json/jwt-auth/v1/token. Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.

If I just use this code

```
<IfModule mod_rewrite.c>
RewriteEngine on
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
</IfModule>
```

 I get this error

XMLHttpRequest cannot load http://site.com/wp-json/jwt-auth/v1/token. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://remotesite.com' is therefore not allowed access.

Looks like i got farther but then the WP site breaks

Any Ideas on what I am doing wrong?

**Comment by ghost** [comment]
Switching them around, worked for me

<IfModule mod_rewrite.c>
RewriteEngine on
RewriteCond %{HTTP:Authorization} ^(._)
RewriteRule ^(._) - [E=HTTP_AUTHORIZATION:%1]
</IfModule>

<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

**Comment by Tmeister** [comment]
```
RewriteEngine on 
RewriteCond %{HTTP:Authorization} ^(._) 
RewriteRule ^(._) - [E=HTTP_AUTHORIZATION:%1] 

RewriteEngine On 
RewriteBase / 
RewriteRule ^index.php$ - [L] 
RewriteCond %{REQUEST_FILENAME} !-f 
RewriteCond %{REQUEST_FILENAME} !-d 
RewriteRule . /index.php [L]
```

**Comment by simonh1000** [comment]
unfortunately, this didn't help on my dev machine :-(
