### ISSUE TITLE
/wp-json/jwt-auth/... NOT FOUND

### ISSUE THREAD

**Issue by simonesummo** [Tmeister/wp-api-jwt-auth#94]
I’m using for the first time this plugin on a today project, but I got the error “POST http://localhost:8100/server/wp-json/jwt-auth/v1/token 404 (Not Found)” in the console; looks like it didn’t create the folder wp-json/etc…

Thanks a lot!!

**Comment by jrsarath** [comment]
Did you installed WP REST API plugin ?
https://wordpress.org/plugins/rest-api/

**Comment by davewolfe** [comment]
I'm having this issue and WP REST API is installed. The specific error is: {"No route was found matching the URL and request method"}. I disabled all other plugins except this and the WP REST API.

**Comment by jrsarath** [comment]
> I’m using for the first time this plugin on a today project, but I got the error “POST http://localhost:8100/server/wp-json/jwt-auth/v1/token 404 (Not Found)” in the console; looks like it didn’t create the folder wp-json/etc…

First of all it doesn't actually creates any wp-json folder.. 
wp-rest api plugin creates a End Point named http://domain/wp-json

**Make sure you are using the url in this fomat**
`http://domainname/wp-json/jwt-auth/v1/token`
with method POST.
if it still fails then try to load 
`http://domainname/wp-json/`
into your browser, and let me know what it shows..

**Comment by Steffi3rd** [comment]
Make sure you have enabled Pretty Permalinks in your Wordpress Settings, to be able to use ‘/wp-json’

Otherwise it will be ´?rest_route=´
