### ISSUE TITLE
UI admin branch

### ISSUE THREAD

**Issue by alaa-alsalehi** [Tmeister/wp-api-jwt-auth#96]
what is the situation of this branch
really I want to use it
it looks like @Tmeister does not have a time for it
so anyone can tell me if it is ready to use?

**Comment by tzkmx** [comment]
It's ready to use, if for some use case does not fits, check for the issues of others users, maybe there is a patch for it already.

**Comment by alaa-alsalehi** [comment]
@tzkmx already I used it
thank you
