### ISSUE TITLE
Can't get correct user ID

### ISSUE THREAD

**Issue by HiepVu511** [Tmeister/wp-api-jwt-auth#98]
I can’t get current user ID with wp_get_current_user()->ID or get_current_user_id(), it always returns 0 for every API call with retrieved token . And if I switch to basic auth method, everything work as expected.
Is this a bug and are there any workaround for this issue?

**Comment by jrsarath** [comment]
JWT token is working fine for me, im using with this plugin with javascript client. 
`$(function () {
            var base64Url = TOKEN_HERE.split('.')[1];
            var base64 = base64Url.replace('-', '+').replace('_', '/');
            var jwt_data = JSON.parse(window.atob(base64));
            localStorage.setItem("currentUserId", jwt_data.data.user.id);
        });`
returns the user id correctly

**Comment by kkjdroid** [comment]
I'm having the same problem, and parsing it client-side is unacceptable for my use case. @Tmeister, any ideas?

**Comment by jrsarath** [comment]
@kkjdroid you can decode the JWT token to get client id

**Comment by kkjdroid** [comment]
I specifically said that that won't work for my use case. I need the user ID to be available serverside, and I need to make sure that it can't be spoofed.

**Comment by kkjdroid** [comment]
I found a solution that seems to work. Instead of calling `get_loggedin_user_id()`, call `apply_filters('determine_current_user', false)`.

**Comment by juanjosuem** [comment]
i am having the same problem, any new solution, nothing works

**Comment by kbedra-tbscg** [comment]
> I found a solution that seems to work. Instead of calling `get_loggedin_user_id()`, call `apply_filters('determine_current_user', false)`.

Thanks a lot. That's a working solution for me. In response of this call i got user id and `wp_get_current_user()` is returning user object

**Comment by rocifier** [comment]
I'm really confused about this solution. According to this plugin's description it is supposed to set up the current user based on the token. But that isn't working for me either, wp_get_current_user() always returns a default object (with ID = 0). Am I supposed to write a hook  for determine_current_user? I tried calling it as above, but it returned 0 and the current user wasn't sent. I'm sure I'm sending a recent Bearer token properly to my custom wp-json route. 

EDIT: I found there is no bug, but the wordpress default .htaccess doesn't pass through the Authorization header. After ammending .htaccess the plugin and above situation works for me.

**Comment by hfoletto** [comment]
> I found a solution that seems to work. Instead of calling `get_loggedin_user_id()`, call `apply_filters('determine_current_user', false)`.

Thank you, it worked for me!
However I'm still wondering why it didn't work with `get_current_user_id`, but it did with `apply_filters('determine_current_user', false)`...

The most weird is that using postman it works with both, only when using the production web app I faced this problem.

**Comment by rocifier** [comment]
@hfoletto what was the result when you used wp_get_current_user()?

**Comment by charlie-cheetah** [comment]
Just a small note - I had a problem with REST calls and JWT token, the user couldn't be recognized. The problem was with cookies, after removing cookies from REST calls, and leaving only header with token, it was working again.

**Comment by hfoletto** [comment]
> @hfoletto what was the result when you used wp_get_current_user()?

@rocifier it just returns 0, which according to the documentation, it's the default if no user is logged in: https://developer.wordpress.org/reference/functions/get_current_user_id/

> Just a small note - I had a problem with REST calls and JWT token, the user couldn't be recognized. The problem was with cookies, after removing cookies from REST calls, and leaving only header with token, it was working again.

@charlie-cheetah may I ask how did you do it? I think that this may be the issue, because otherwise it wouldn't work on postman either.

**Comment by charlie-cheetah** [comment]
> @charlie-cheetah may I ask how did you do it? I think that this may be the issue, because otherwise it wouldn't work on postman either.

I used fetch with credentianls: 'omit' option, it's removing cookies from request header
```
    const requestOptions = {
        method: 'GET',
        credentials: 'omit',
        headers: authHeader()
    }

    return fetch(url, requestOptions)
        .then(handleResponse())
```

authHeader() function returns my JWT token

**Comment by hfoletto** [comment]
> > @charlie-cheetah may I ask how did you do it? I think that this may be the issue, because otherwise it wouldn't work on postman either.
> 
> I used fetch with credentianls: 'omit' option, it's removing cookies from request header
> 
> ```
>     const requestOptions = {
>         method: 'GET',
>         credentials: 'omit',
>         headers: authHeader()
>     }
> 
>     return fetch(url, requestOptions)
>         .then(handleResponse())
> ```
> authHeader() function returns my JWT token

@charlie-cheetah That did the trick, thank you!
